create schema if not exists private;
revoke all on schema private from public;
revoke all on schema private from anon, authenticated;

create table if not exists public.btc_data_sources (
  source_key text primary key,
  category text not null,
  display_name text not null,
  base_url text,
  priority integer not null default 100,
  enabled boolean not null default true,
  expected_mode text not null default 'REST',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.btc_exchange_snapshots (
  id bigint generated by default as identity primary key,
  observed_at timestamptz not null default now(),
  source_key text references public.btc_data_sources(source_key),
  venue text not null,
  market_type text not null check (market_type in ('spot','perp','futures','options','index')),
  symbol text not null,
  price_usd numeric,
  bid_usd numeric,
  ask_usd numeric,
  spread_bps numeric,
  volume_usd_24h numeric,
  open_interest_usd numeric,
  funding_rate numeric,
  funding_interval_hours numeric,
  taker_buy_usd_1m numeric,
  taker_sell_usd_1m numeric,
  cvd_usd_1m numeric,
  sample_trade_count integer,
  sample_coverage_ms integer,
  data_status text not null default 'LIVE' check (data_status in ('LIVE','DELAYED','ESTIMATED','PRELIMINARY','FINAL','STALE','PARTIAL','UNAVAILABLE')),
  source_event_at timestamptz,
  received_at timestamptz not null default now(),
  latency_ms integer,
  sequence_ok boolean,
  quality_score numeric check (quality_score between 0 and 100),
  raw jsonb not null default '{}'::jsonb
);
create index if not exists btc_exchange_snapshots_observed_idx on public.btc_exchange_snapshots (observed_at desc);
create index if not exists btc_exchange_snapshots_venue_market_idx on public.btc_exchange_snapshots (venue, market_type, observed_at desc);

create table if not exists public.btc_market_snapshots (
  id bigint generated by default as identity primary key,
  observed_at timestamptz not null default now(),
  composite_price_usd numeric,
  composite_method text,
  venue_count integer,
  venue_dispersion_bps numeric,
  spot_cvd_usd_1m numeric,
  spot_cvd_usd_5m numeric,
  spot_cvd_usd_15m numeric,
  spot_cvd_usd_1h numeric,
  perp_cvd_usd_1m numeric,
  perp_cvd_usd_5m numeric,
  perp_cvd_usd_15m numeric,
  perp_cvd_usd_1h numeric,
  spot_perp_cvd_divergence_5m numeric,
  open_interest_usd numeric,
  oi_delta_usd_1m numeric,
  oi_delta_pct_1m numeric,
  oi_delta_usd_5m numeric,
  oi_delta_pct_5m numeric,
  oi_delta_usd_15m numeric,
  oi_delta_pct_15m numeric,
  oi_delta_usd_1h numeric,
  oi_delta_pct_1h numeric,
  funding_simple_avg numeric,
  funding_oi_weighted numeric,
  funding_volume_weighted numeric,
  long_liquidations_usd_1m numeric,
  short_liquidations_usd_1m numeric,
  long_liquidations_usd_5m numeric,
  short_liquidations_usd_5m numeric,
  liquidation_velocity_usd_per_min numeric,
  nearest_liquidity_above_usd numeric,
  nearest_liquidity_below_usd numeric,
  nearest_liquidity_above_notional_usd numeric,
  nearest_liquidity_below_notional_usd numeric,
  driver_classification text check (driver_classification in ('SPOT_LED','LEVERAGE_LED','MIXED','UNCLEAR')),
  driver_confidence numeric check (driver_confidence between 0 and 100),
  data_quality numeric check (data_quality between 0 and 100),
  freshness jsonb not null default '{}'::jsonb,
  source_health jsonb not null default '{}'::jsonb,
  raw jsonb not null default '{}'::jsonb
);
create index if not exists btc_market_snapshots_observed_idx on public.btc_market_snapshots (observed_at desc);

create table if not exists public.btc_liquidation_clusters (
  id bigint generated by default as identity primary key,
  observed_at timestamptz not null default now(),
  horizon text not null,
  side text not null check (side in ('above','below')),
  price_usd numeric not null,
  estimated_notional_usd numeric,
  distance_pct numeric,
  provider text not null,
  data_status text not null default 'ESTIMATED' check (data_status in ('LIVE','DELAYED','ESTIMATED','PRELIMINARY','FINAL','STALE','PARTIAL','UNAVAILABLE')),
  methodology text,
  raw jsonb not null default '{}'::jsonb
);
create index if not exists btc_liq_clusters_obs_idx on public.btc_liquidation_clusters (observed_at desc, horizon, side);

create table if not exists public.btc_signal_state (
  singleton boolean primary key default true check (singleton),
  updated_at timestamptz not null default now(),
  primary_regime text,
  secondary_regime text,
  regime_confidence numeric check (regime_confidence between 0 and 100),
  bull_score numeric check (bull_score between 0 and 100),
  bear_score numeric check (bear_score between 0 and 100),
  trade_confidence numeric check (trade_confidence between 0 and 100),
  event_risk text check (event_risk in ('LOW','MEDIUM','HIGH','EXTREME')),
  preferred_action text,
  active_setup jsonb not null default '{}'::jsonb,
  watchlist jsonb not null default '[]'::jsonb,
  explainability jsonb not null default '{}'::jsonb
);
insert into public.btc_signal_state(singleton) values (true) on conflict (singleton) do nothing;

create table if not exists public.btc_setups (
  id bigint generated by default as identity primary key,
  detected_at timestamptz not null default now(),
  status text not null default 'WATCH' check (status in ('WATCH','TRIGGERED','INVALIDATED','EXPIRED','CLOSED')),
  setup_type text not null,
  direction text not null check (direction in ('LONG','SHORT','NEUTRAL')),
  time_horizon text,
  confidence numeric check (confidence between 0 and 100),
  data_quality numeric check (data_quality between 0 and 100),
  entry_zone jsonb,
  trigger_required text,
  invalidation text,
  stop_risk_level numeric,
  targets jsonb,
  expected_rr numeric,
  key_levels jsonb,
  evidence jsonb not null default '{}'::jsonb,
  contradictions jsonb not null default '[]'::jsonb,
  cancel_conditions jsonb not null default '[]'::jsonb,
  expires_at timestamptz,
  outcome jsonb,
  updated_at timestamptz not null default now()
);
create index if not exists btc_setups_status_idx on public.btc_setups (status, detected_at desc);

create table if not exists public.btc_alerts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  priority text not null check (priority in ('INFO','WATCH','HIGH','CRITICAL')),
  alert_type text not null,
  dedupe_key text,
  title text not null,
  payload jsonb not null,
  delivered_channels jsonb not null default '[]'::jsonb,
  delivered_at timestamptz
);
create unique index if not exists btc_alerts_dedupe_idx on public.btc_alerts (dedupe_key) where dedupe_key is not null;

insert into public.btc_data_sources(source_key,category,display_name,base_url,priority,expected_mode,notes) values
 ('binance_ws','exchange','Binance WebSocket','wss://stream.binance.com',10,'WEBSOCKET','Primary spot stream'),
 ('binance_futures_ws','exchange','Binance Futures WebSocket','wss://fstream.binance.com',10,'WEBSOCKET','Primary perp stream'),
 ('bybit_ws','exchange','Bybit WebSocket','wss://stream.bybit.com',20,'WEBSOCKET','Spot and linear perp with reconstructed order book'),
 ('okx_ws','exchange','OKX WebSocket','wss://ws.okx.com:8443',30,'WEBSOCKET','Spot and perp order books'),
 ('coinbase_public','exchange','Coinbase Public','https://api.exchange.coinbase.com',40,'REST','USD spot reference'),
 ('coinglass','aggregator','CoinGlass','https://open-api-v4.coinglass.com',5,'API','Aggregation/liquidation enrichment')
on conflict (source_key) do update set display_name=excluded.display_name,base_url=excluded.base_url,priority=excluded.priority,expected_mode=excluded.expected_mode,notes=excluded.notes,updated_at=now();

create or replace view public.btc_latest_state as
select * from public.btc_market_snapshots order by observed_at desc limit 1;

create or replace view public.btc_current_intelligence as
select m.*, s.primary_regime, s.secondary_regime, s.regime_confidence, s.bull_score, s.bear_score,
       s.trade_confidence, s.event_risk, s.preferred_action, s.active_setup, s.watchlist, s.explainability
from public.btc_latest_state m
cross join public.btc_signal_state s
where s.singleton = true;

create or replace function private.btc_prune_history()
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
begin
  delete from public.btc_exchange_snapshots where observed_at < now() - interval '30 days';
  delete from public.btc_market_snapshots where observed_at < now() - interval '180 days';
  delete from public.btc_liquidation_clusters where observed_at < now() - interval '30 days';
end;
$$;
revoke all on function private.btc_prune_history() from public;
revoke all on function private.btc_prune_history() from anon, authenticated;
grant execute on function private.btc_prune_history() to service_role;

alter table public.btc_data_sources enable row level security;
alter table public.btc_exchange_snapshots enable row level security;
alter table public.btc_market_snapshots enable row level security;
alter table public.btc_liquidation_clusters enable row level security;
alter table public.btc_signal_state enable row level security;
alter table public.btc_setups enable row level security;
alter table public.btc_alerts enable row level security;

revoke all on public.btc_data_sources from anon, authenticated;
revoke all on public.btc_exchange_snapshots from anon, authenticated;
revoke all on public.btc_market_snapshots from anon, authenticated;
revoke all on public.btc_liquidation_clusters from anon, authenticated;
revoke all on public.btc_signal_state from anon, authenticated;
revoke all on public.btc_setups from anon, authenticated;
revoke all on public.btc_alerts from anon, authenticated;
