-- BTC Global Intelligence v3 durable feature store.
-- Railway is the single authoritative compute/ingestion engine; Supabase is
-- durable state, configuration and audit history only.

create table if not exists public.btc_feature_snapshots (
  id bigint generated by default as identity primary key,
  observed_at timestamptz not null default now(),
  engine_version text not null,
  price_usd numeric,
  structure jsonb not null default '{}'::jsonb,
  external jsonb not null default '{}'::jsonb,
  signal jsonb not null default '{}'::jsonb,
  coverage jsonb not null default '{}'::jsonb
);
create index if not exists btc_feature_snapshots_observed_idx on public.btc_feature_snapshots(observed_at desc);

create table if not exists public.btc_macro_events (
  id bigint generated by default as identity primary key,
  event_key text not null,
  scheduled_at timestamptz,
  released_at timestamptz,
  event_name text not null,
  source text not null,
  status text not null default 'SCHEDULED' check (status in ('SCHEDULED','LIVE','PRELIMINARY','FINAL','REVISED','CANCELLED','UNAVAILABLE')),
  actual numeric,
  consensus numeric,
  previous numeric,
  revision numeric,
  surprise numeric,
  units text,
  importance text check (importance in ('LOW','MEDIUM','HIGH','CRITICAL')),
  btc_pre_context jsonb not null default '{}'::jsonb,
  btc_post_reaction jsonb not null default '{}'::jsonb,
  raw jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
create unique index if not exists btc_macro_events_key_idx on public.btc_macro_events(event_key);
create index if not exists btc_macro_events_time_idx on public.btc_macro_events(scheduled_at desc);

create table if not exists public.btc_options_snapshots (
  id bigint generated by default as identity primary key,
  observed_at timestamptz not null default now(),
  source text not null,
  dvol numeric,
  realized_vol numeric,
  atm_iv numeric,
  put_call_oi_ratio numeric,
  put_call_volume_ratio numeric,
  total_open_interest numeric,
  expected_move jsonb not null default '{}'::jsonb,
  term_structure jsonb not null default '[]'::jsonb,
  skew jsonb not null default '{}'::jsonb,
  expiries jsonb not null default '[]'::jsonb,
  strikes jsonb not null default '[]'::jsonb,
  gamma_context jsonb not null default '{}'::jsonb,
  max_pain jsonb not null default '{}'::jsonb,
  data_status text not null default 'LIVE' check (data_status in ('LIVE','DELAYED','ESTIMATED','PRELIMINARY','FINAL','STALE','PARTIAL','UNAVAILABLE')),
  raw jsonb not null default '{}'::jsonb
);
create index if not exists btc_options_snapshots_time_idx on public.btc_options_snapshots(observed_at desc);

create table if not exists public.btc_prediction_market_snapshots (
  id bigint generated by default as identity primary key,
  observed_at timestamptz not null default now(),
  provider text not null check (provider in ('POLYMARKET','KALSHI')),
  market_id text not null,
  title text not null,
  probability numeric,
  bid numeric,
  ask numeric,
  liquidity numeric,
  volume_24h numeric,
  open_interest numeric,
  closes_at timestamptz,
  relevance_score numeric,
  raw jsonb not null default '{}'::jsonb
);
create index if not exists btc_prediction_market_time_idx on public.btc_prediction_market_snapshots(observed_at desc, provider);
create index if not exists btc_prediction_market_market_idx on public.btc_prediction_market_snapshots(provider, market_id, observed_at desc);

create table if not exists public.btc_news_events (
  id bigint generated by default as identity primary key,
  observed_at timestamptz not null default now(),
  published_at timestamptz,
  source text not null,
  source_tier smallint not null default 1,
  headline text not null,
  category text,
  relevance numeric,
  novelty numeric,
  credibility numeric,
  magnitude numeric,
  direction text check (direction in ('BULLISH','BEARISH','NEUTRAL','MIXED','UNKNOWN')),
  priced_in numeric,
  btc_reaction jsonb not null default '{}'::jsonb,
  dedupe_hash text,
  raw jsonb not null default '{}'::jsonb
);
create unique index if not exists btc_news_events_dedupe_idx on public.btc_news_events(dedupe_hash) where dedupe_hash is not null;
create index if not exists btc_news_events_time_idx on public.btc_news_events(coalesce(published_at, observed_at) desc);

create table if not exists public.btc_cross_asset_snapshots (
  id bigint generated by default as identity primary key,
  observed_at timestamptz not null default now(),
  dxy numeric,
  nasdaq numeric,
  sp500 numeric,
  vix numeric,
  move numeric,
  gold numeric,
  wti numeric,
  brent numeric,
  usdjpy numeric,
  usdcnh numeric,
  credit jsonb not null default '{}'::jsonb,
  crypto_equities jsonb not null default '{}'::jsonb,
  rolling_correlations jsonb not null default '{}'::jsonb,
  raw jsonb not null default '{}'::jsonb
);
create index if not exists btc_cross_asset_time_idx on public.btc_cross_asset_snapshots(observed_at desc);

create table if not exists public.btc_onchain_snapshots (
  id bigint generated by default as identity primary key,
  observed_at timestamptz not null default now(),
  exchange_flows jsonb not null default '{}'::jsonb,
  exchange_reserves jsonb not null default '{}'::jsonb,
  realized_metrics jsonb not null default '{}'::jsonb,
  mvrv numeric,
  sopr numeric,
  nupl numeric,
  sth_lth jsonb not null default '{}'::jsonb,
  miners jsonb not null default '{}'::jsonb,
  hash_rate numeric,
  difficulty numeric,
  stablecoins jsonb not null default '{}'::jsonb,
  whales jsonb not null default '[]'::jsonb,
  data_status text not null default 'PARTIAL' check (data_status in ('LIVE','DELAYED','ESTIMATED','PRELIMINARY','FINAL','STALE','PARTIAL','UNAVAILABLE')),
  raw jsonb not null default '{}'::jsonb
);
create index if not exists btc_onchain_time_idx on public.btc_onchain_snapshots(observed_at desc);

alter table public.btc_feature_snapshots enable row level security;
alter table public.btc_macro_events enable row level security;
alter table public.btc_options_snapshots enable row level security;
alter table public.btc_prediction_market_snapshots enable row level security;
alter table public.btc_news_events enable row level security;
alter table public.btc_cross_asset_snapshots enable row level security;
alter table public.btc_onchain_snapshots enable row level security;

revoke all on public.btc_feature_snapshots from anon, authenticated;
revoke all on public.btc_macro_events from anon, authenticated;
revoke all on public.btc_options_snapshots from anon, authenticated;
revoke all on public.btc_prediction_market_snapshots from anon, authenticated;
revoke all on public.btc_news_events from anon, authenticated;
revoke all on public.btc_cross_asset_snapshots from anon, authenticated;
revoke all on public.btc_onchain_snapshots from anon, authenticated;

create or replace function private.btc_prune_v3_history()
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
begin
  delete from public.btc_feature_snapshots where observed_at < now() - interval '365 days';
  delete from public.btc_options_snapshots where observed_at < now() - interval '365 days';
  delete from public.btc_prediction_market_snapshots where observed_at < now() - interval '180 days';
  delete from public.btc_cross_asset_snapshots where observed_at < now() - interval '365 days';
  delete from public.btc_onchain_snapshots where observed_at < now() - interval '730 days';
end;
$$;
revoke all on function private.btc_prune_v3_history() from public;
revoke all on function private.btc_prune_v3_history() from anon, authenticated;
grant execute on function private.btc_prune_v3_history() to service_role;
