import WebSocket from 'ws';
import { BybitBookReconstructor } from './bybit-book.js';
import { OrderBookState } from './orderbook-state.js';

const num=v=>{if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)?n:null};
const now=()=>new Date().toISOString();

export class DirectMarketHub {
  constructor({flow,clickhouseWriter,redisPublisher,structureEngine,log,bookSampleMs=1000}={}){
    this.flow=flow;this.clickhouseWriter=clickhouseWriter;this.redisPublisher=redisPublisher;this.structureEngine=structureEngine;this.log=log;this.bookSampleMs=bookSampleMs;
    this.sockets={};this.books=new Map();this.lastBookSample=new Map();this.errors=[];this.stoppers=[];this.derivatives={};this.okxCtVal=null;this.liquidations=[];this.started=false;
  }
  error(err,context){const x={at:now(),context,error:String(err)};this.errors.push(x);if(this.errors.length>100)this.errors.shift();this.log?.warn?.(x)}
  health(name,patch){this.sockets[name]={...(this.sockets[name]||{}),...patch}}
  trade({venue,market_type,symbol,price,qty,side,event_time_ms,trade_id=null,notional_usd=null}){
    const p=num(price),q=num(qty),t=num(event_time_ms);if(!p||!q||!t||!['buy','sell'].includes(side))return;
    const row={event_time:new Date(t).toISOString(),ingested_at:now(),event_time_ms:t,venue,market_type,symbol,price:p,qty:q,notional_usd:num(notional_usd)??p*q,side,trade_id:String(trade_id??'')};
    this.flow.recordTrade(row);this.structureEngine?.recordTrade(row);this.clickhouseWriter.enqueueTrade(row);
  }
  book({venue,market_type,symbol,event_time_ms,bids,asks,sequence=null}){
    const norm=x=>Array.isArray(x)?[x[0],x[1]]:[x.price??x.px,x.qty??x.size??x.sz];
    bids=(bids||[]).map(norm).filter(x=>num(x[0])&&num(x[1])).sort((a,b)=>Number(b[0])-Number(a[0]));asks=(asks||[]).map(norm).filter(x=>num(x[0])&&num(x[1])).sort((a,b)=>Number(a[0])-Number(b[0]));if(!bids.length||!asks.length)return;
    const bid=num(bids[0][0]),ask=num(asks[0][0]);if(!bid||!ask||ask<=bid)return;const mid=(bid+ask)/2,t=num(event_time_ms)||Date.now();const row={event_time:new Date(t).toISOString(),ingested_at:now(),event_time_ms:t,venue,market_type,symbol,sequence:String(sequence??''),bid_prices:bids.slice(0,50).map(x=>Number(x[0])),bid_sizes:bids.slice(0,50).map(x=>Number(x[1])),ask_prices:asks.slice(0,50).map(x=>Number(x[0])),ask_sizes:asks.slice(0,50).map(x=>Number(x[1])),best_bid:bid,best_ask:ask,spread_bps:(ask-bid)/mid*10000};
    const k=`${venue}:${market_type}`;this.books.set(k,row);void this.redisPublisher.publishBook(row);const last=this.lastBookSample.get(k)||0;if(Date.now()-last>=this.bookSampleMs){this.lastBookSample.set(k,Date.now());this.clickhouseWriter.enqueueBook(row)}
  }
  socket(name,url,{onOpen,onMessage,onReset,appPing=null,headers={}}={}){
    let ws,closed=false,attempt=0,pingTimer,watchdog;const start=()=>{if(closed)return;attempt++;this.health(name,{status:'CONNECTING',attempt,url});onReset?.();ws=new WebSocket(url,{headers});
      ws.on('open',()=>{attempt=0;this.health(name,{status:'LIVE',connected_at:now(),last_message_at:null});try{onOpen?.(ws)}catch(e){this.error(e,`${name}:open`)}pingTimer=setInterval(()=>{try{if(ws.readyState!==WebSocket.OPEN)return;if(appPing!==null)ws.send(typeof appPing==='string'?appPing:JSON.stringify(appPing));else ws.ping()}catch(e){this.error(e,`${name}:ping`)}},20000);watchdog=setInterval(()=>{const h=this.sockets[name],last=h?.last_message_at?Date.parse(h.last_message_at):0;if(last&&Date.now()-last>45000){this.health(name,{status:'STALE'});try{ws.terminate()}catch{}}},10000)});
      ws.on('message',buf=>{this.health(name,{status:'LIVE',last_message_at:now()});try{onMessage?.(JSON.parse(buf.toString()),ws)}catch(e){this.error(e,`${name}:message`)}});ws.on('error',e=>this.error(e,`${name}:socket`));ws.on('close',()=>{clearInterval(pingTimer);clearInterval(watchdog);onReset?.();this.health(name,{status:'DISCONNECTED',disconnected_at:now()});setTimeout(start,Math.min(30000,1000*2**Math.min(attempt,5)))})};start();const stop=()=>{closed=true;clearInterval(pingTimer);clearInterval(watchdog);onReset?.();try{ws?.close()}catch{}};this.stoppers.push(stop);return stop;
  }
  async _json(url,timeout=4000){const c=new AbortController(),tm=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{headers:{accept:'application/json'},signal:c.signal});if(!r.ok)throw new Error(`${r.status} ${url}`);return await r.json()}finally{clearTimeout(tm)}}

  _binance(){
    this.socket('binance_spot','wss://stream.binance.com:9443/stream?streams=btcusdt@aggTrade/btcusdt@depth20@100ms',{onMessage:m=>{const d=m.data||m;if(m.stream?.includes('aggTrade'))this.trade({venue:'Binance',market_type:'spot',symbol:'BTCUSDT',price:d.p,qty:d.q,side:d.m?'sell':'buy',event_time_ms:d.T,trade_id:d.a});else if(m.stream?.includes('depth'))this.book({venue:'Binance',market_type:'spot',symbol:'BTCUSDT',event_time_ms:d.E||Date.now(),bids:d.bids||d.b,asks:d.asks||d.a,sequence:d.lastUpdateId||d.u})}});
    this.socket('binance_perp','wss://fstream.binance.com/stream?streams=btcusdt@aggTrade/btcusdt@depth20@100ms',{onMessage:m=>{const d=m.data||m;if(m.stream?.includes('aggTrade'))this.trade({venue:'Binance',market_type:'perp',symbol:'BTCUSDT-PERP',price:d.p,qty:d.q,side:d.m?'sell':'buy',event_time_ms:d.T,trade_id:d.a});else if(m.stream?.includes('depth'))this.book({venue:'Binance',market_type:'perp',symbol:'BTCUSDT-PERP',event_time_ms:d.E||Date.now(),bids:d.b,asks:d.a,sequence:d.u})}})
  }
  _bybit(){for(const[category,market]of[['spot','spot'],['linear','perp']]){const r=new BybitBookReconstructor({depth:50});this.socket(`bybit_${market}`,`wss://stream.bybit.com/v5/public/${category}`,{appPing:{op:'ping'},onReset:()=>r.reset(),onOpen:ws=>ws.send(JSON.stringify({op:'subscribe',args:['publicTrade.BTCUSDT','orderbook.50.BTCUSDT']})),onMessage:m=>{if(m.topic==='publicTrade.BTCUSDT')for(const t of m.data||[])this.trade({venue:'Bybit',market_type:market,symbol:market==='spot'?'BTCUSDT':'BTCUSDT-PERP',price:t.p,qty:t.v,side:String(t.S).toLowerCase()==='buy'?'buy':'sell',event_time_ms:t.T||m.ts,trade_id:t.i});if(m.topic==='orderbook.50.BTCUSDT'){const a=r.applyMessage(m);if(!a.book){this.health(`bybit_${market}`,{status:a.status==='WAITING_SNAPSHOT'?'PARTIAL':'LIVE',book_status:a.status});return}this.book({venue:'Bybit',market_type:market,symbol:market==='spot'?'BTCUSDT':'BTCUSDT-PERP',event_time_ms:m.cts||m.ts||Date.now(),bids:a.book.bids,asks:a.book.asks,sequence:a.book.seq})}}})}}
  async _okx(){try{const j=await this._json('https://www.okx.com/api/v5/public/instruments?instType=SWAP&instId=BTC-USDT-SWAP');this.okxCtVal=num(j.data?.[0]?.ctVal)}catch(e){this.error(e,'okx:contract')}
    for(const[inst,market]of[['BTC-USDT','spot'],['BTC-USDT-SWAP','perp']])this.socket(`okx_${market}`,'wss://ws.okx.com:8443/ws/v5/public',{appPing:'ping',onOpen:ws=>ws.send(JSON.stringify({op:'subscribe',args:[{channel:'trades',instId:inst},{channel:'books5',instId:inst}]})),onMessage:m=>{if(m.arg?.channel==='trades')for(const t of m.data||[]){let q=num(t.sz);if(market==='perp'){if(!this.okxCtVal)return;q*=this.okxCtVal}this.trade({venue:'OKX',market_type:market,symbol:inst,price:t.px,qty:q,side:t.side,event_time_ms:t.ts,trade_id:t.tradeId})}if(m.arg?.channel==='books5')for(const b of m.data||[])this.book({venue:'OKX',market_type:market,symbol:inst,event_time_ms:b.ts||Date.now(),bids:b.bids,asks:b.asks,sequence:b.seqId})}})
  }
  _coinbase(){const book=new OrderBookState({depth:50});this.socket('coinbase_spot','wss://advanced-trade-ws.coinbase.com',{onReset:()=>book.reset(),onOpen:ws=>{for(const channel of ['heartbeats','market_trades','level2'])ws.send(JSON.stringify({type:'subscribe',product_ids:channel==='heartbeats'?[]:['BTC-USD'],channel}))},onMessage:m=>{for(const e of m.events||[]){if(Array.isArray(e.trades))for(const t of e.trades){/* Coinbase side is maker side, so taker/aggressor is opposite. */const maker=String(t.side).toUpperCase();this.trade({venue:'Coinbase',market_type:'spot',symbol:'BTC-USD',price:t.price,qty:t.size,side:maker==='BUY'?'sell':'buy',event_time_ms:Date.parse(t.time)||Date.parse(m.timestamp)||Date.now(),trade_id:t.trade_id})}if(Array.isArray(e.updates)){const bids=[],asks=[];for(const u of e.updates){const x=[u.price_level,u.new_quantity];(String(u.side).toLowerCase()==='bid'?bids:asks).push(x)}const view=e.type==='snapshot'?book.snapshot({bids,asks,sequence:m.sequence_num,time:Date.parse(m.timestamp)||Date.now()}):book.update({bids,asks,sequence:m.sequence_num,time:Date.parse(m.timestamp)||Date.now()});if(view&&!view.gap&&view.bids.length&&view.asks.length)this.book({venue:'Coinbase',market_type:'spot',symbol:'BTC-USD',event_time_ms:view.time||Date.now(),bids:view.bids,asks:view.asks,sequence:view.sequence})}}}})}
  _kraken(){const book=new OrderBookState({depth:50});this.socket('kraken_spot','wss://ws.kraken.com/v2',{onReset:()=>book.reset(),onOpen:ws=>{ws.send(JSON.stringify({method:'subscribe',params:{channel:'trade',symbol:['BTC/USD'],snapshot:false}}));ws.send(JSON.stringify({method:'subscribe',params:{channel:'book',symbol:['BTC/USD'],depth:25,snapshot:true}}))},onMessage:m=>{if(m.channel==='trade')for(const t of m.data||[])this.trade({venue:'Kraken',market_type:'spot',symbol:'BTC/USD',price:t.price,qty:t.qty,side:t.side==='buy'?'buy':'sell',event_time_ms:Date.parse(t.timestamp)||Date.now(),trade_id:t.trade_id});if(m.channel==='book')for(const b of m.data||[]){const bids=(b.bids||[]).map(x=>[x.price,x.qty]),asks=(b.asks||[]).map(x=>[x.price,x.qty]);const view=m.type==='snapshot'||!book.initialized?book.snapshot({bids,asks,sequence:m.sequence,time:Date.parse(b.timestamp)||Date.now()}):book.update({bids,asks,sequence:m.sequence,time:Date.parse(b.timestamp)||Date.now()});if(view&&!view.gap&&view.bids.length&&view.asks.length)this.book({venue:'Kraken',market_type:'spot',symbol:'BTC/USD',event_time_ms:view.time,bids:view.bids,asks:view.asks,sequence:view.sequence})}}})}
  _hyperliquid(){this.socket('hyperliquid_perp','wss://api.hyperliquid.xyz/ws',{onOpen:ws=>{ws.send(JSON.stringify({method:'subscribe',subscription:{type:'trades',coin:'BTC'}}));ws.send(JSON.stringify({method:'subscribe',subscription:{type:'l2Book',coin:'BTC'}}))},onMessage:m=>{if(m.channel==='trades')for(const t of m.data||[])this.trade({venue:'Hyperliquid',market_type:'perp',symbol:'BTC-PERP',price:t.px,qty:t.sz,side:t.side==='B'?'buy':'sell',event_time_ms:t.time||Date.now(),trade_id:t.hash});if(m.channel==='l2Book'){const levels=m.data?.levels||[];if(levels[0]?.length&&levels[1]?.length)this.book({venue:'Hyperliquid',market_type:'perp',symbol:'BTC-PERP',event_time_ms:m.data?.time||Date.now(),bids:levels[0],asks:levels[1]})}}})}
  _deribit(){const book=new OrderBookState({depth:50});this.socket('deribit_perp','wss://www.deribit.com/ws/api/v2',{onReset:()=>book.reset(),onOpen:ws=>ws.send(JSON.stringify({jsonrpc:'2.0',id:1,method:'public/subscribe',params:{channels:['trades.BTC-PERPETUAL.100ms','book.BTC-PERPETUAL.100ms']}})),onMessage:m=>{if(m.method!=='subscription')return;const ch=m.params?.channel||'',d=m.params?.data;if(ch.startsWith('trades.'))for(const t of d||[]){const usd=num(t.amount),p=num(t.price);if(usd&&p)this.trade({venue:'Deribit',market_type:'perp',symbol:'BTC-PERPETUAL',price:p,qty:usd/p,notional_usd:usd,side:t.direction==='buy'?'buy':'sell',event_time_ms:t.timestamp,trade_id:t.trade_id})}if(ch.startsWith('book.')){const view=book.deribit(d);if(view?.gap){this.health('deribit_perp',{status:'PARTIAL',sequence_ok:false});book.reset();return}if(view?.bids?.length&&view?.asks?.length){this.health('deribit_perp',{sequence_ok:true});/* sizes are USD contracts; price levels still valid for liquidity map */this.book({venue:'Deribit',market_type:'perp',symbol:'BTC-PERPETUAL',event_time_ms:view.time||Date.now(),bids:view.bids,asks:view.asks,sequence:view.sequence})}}}})}
  _bitfinex(){const channels=new Map(),book=new OrderBookState({depth:50});this.socket('bitfinex_spot','wss://api-pub.bitfinex.com/ws/2',{onReset:()=>{channels.clear();book.reset()},onOpen:ws=>{ws.send(JSON.stringify({event:'subscribe',channel:'trades',symbol:'tBTCUSD'}));ws.send(JSON.stringify({event:'subscribe',channel:'book',symbol:'tBTCUSD',prec:'P0',freq:'F0',len:'25'}))},onMessage:m=>{if(!Array.isArray(m)){if(m.event==='subscribed')channels.set(m.chanId,m.channel);return}const kind=channels.get(m[0]);if(kind==='trades'){if(Array.isArray(m[1])&&Array.isArray(m[1][0]))return;if((m[1]==='te'||m[1]==='tu')&&Array.isArray(m[2])){const[id,ts,amount,price]=m[2],q=Math.abs(Number(amount));if(q)this.trade({venue:'Bitfinex',market_type:'spot',symbol:'BTCUSD',price,qty:q,side:Number(amount)>0?'buy':'sell',event_time_ms:ts,trade_id:id})}}if(kind==='book'){const rows=Array.isArray(m[1]?.[0])?m[1]:[m[1]],bids=[],asks=[];for(const x of rows){if(!Array.isArray(x))continue;const[p,count,amount]=x;if(Number(count)===0){const side=Number(amount)===1?bids:asks;side.push([p,0]);continue}(Number(amount)>0?bids:asks).push([p,Math.abs(Number(amount))])}const view=!book.initialized&&Array.isArray(m[1]?.[0])?book.snapshot({bids,asks,time:Date.now()}):book.update({bids,asks,time:Date.now()});if(view?.bids?.length&&view?.asks?.length)this.book({venue:'Bitfinex',market_type:'spot',symbol:'BTCUSD',event_time_ms:view.time,bids:view.bids,asks:view.asks})}}})}
  _gate(){const ts=()=>Math.floor(Date.now()/1000);this.socket('gate_spot','wss://api.gateio.ws/ws/v4/',{appPing:{time:ts(),channel:'spot.ping'},onOpen:ws=>{ws.send(JSON.stringify({time:ts(),channel:'spot.trades',event:'subscribe',payload:['BTC_USDT']}));ws.send(JSON.stringify({time:ts(),channel:'spot.order_book',event:'subscribe',payload:['BTC_USDT','20','100ms']}))},onMessage:m=>{if(m.event!=='update')return;if(m.channel==='spot.trades'){const r=m.result;if(r)this.trade({venue:'Gate',market_type:'spot',symbol:'BTC_USDT',price:r.price,qty:r.amount,side:r.side,event_time_ms:num(r.create_time_ms)||m.time_ms||Date.now(),trade_id:r.id})}if(m.channel==='spot.order_book'){const r=m.result;if(r?.bids?.length&&r?.asks?.length)this.book({venue:'Gate',market_type:'spot',symbol:'BTC_USDT',event_time_ms:r.t||m.time_ms||Date.now(),bids:r.bids,asks:r.asks,sequence:r.lastUpdateId})}}});
    this.socket('gate_perp','wss://fx-ws.gateio.ws/v4/ws/usdt',{appPing:{time:ts(),channel:'futures.ping'},headers:{'X-Gate-Size-Decimal':'1'},onOpen:ws=>{ws.send(JSON.stringify({time:ts(),channel:'futures.trades',event:'subscribe',payload:['BTC_USDT']}));ws.send(JSON.stringify({time:ts(),channel:'futures.order_book',event:'subscribe',payload:['BTC_USDT','20','0']}))},onMessage:m=>{if(m.event!=='update')return;if(m.channel==='futures.trades')for(const r of m.result||[]){const size=Number(r.size);if(!size)continue;/* Gate BTC_USDT size is contracts; use public contract multiplier from REST in derivative poll where possible. Mark notional conservatively through price*abs(size) until ctVal resolved is excluded from aggregate CVD by quality layer. */this.trade({venue:'Gate',market_type:'perp',symbol:'BTC_USDT',price:r.price,qty:Math.abs(size),side:size>0?'buy':'sell',event_time_ms:r.create_time_ms||m.time_ms||Date.now(),trade_id:r.id})}if(m.channel==='futures.order_book'){const r=m.result;if(r?.bids?.length&&r?.asks?.length)this.book({venue:'Gate',market_type:'perp',symbol:'BTC_USDT',event_time_ms:m.time_ms||Date.now(),bids:r.bids.map(x=>[x.p,x.s]),asks:r.asks.map(x=>[x.p,x.s]),sequence:r.id})}}})}
  _coinglassLiquidations(){const key=process.env.COINGLASS_API_KEY;if(!key){this.health('coinglass_liquidations',{status:'UNAVAILABLE',reason:'COINGLASS_API_KEY missing'});return}this.socket('coinglass_liquidations',`wss://open-ws.coinglass.com/ws-api?cg-api-key=${encodeURIComponent(key)}`,{appPing:'ping',onOpen:ws=>{ws.send(JSON.stringify({method:'subscribe',channels:['liquidation_orders']}));ws.send(JSON.stringify({method:'subscribe',channels:['liquidationOrders']}))},onMessage:m=>{const rows=m.data||[];for(const r of rows){const base=String(r.base_asset??r.baseAsset??'').toUpperCase();if(base!=='BTC')continue;const side=Number(r.side)===1?'long':'short',event={time:num(r.time)||Date.now(),exchange:r.exchange??r.exName,symbol:r.symbol,price:num(r.price),side,volume_usd:num(r.volume_usd??r.volUsd)||0};this.liquidations.push(event)}const cut=Date.now()-10*60e3;while(this.liquidations.length&&this.liquidations[0].time<cut)this.liquidations.shift()}})}
  liquidationState(){const calc=m=>{const cut=Date.now()-m*60e3,rows=this.liquidations.filter(x=>x.time>=cut);return{long_usd:rows.filter(x=>x.side==='long').reduce((a,x)=>a+x.volume_usd,0),short_usd:rows.filter(x=>x.side==='short').reduce((a,x)=>a+x.volume_usd,0),count:rows.length}};return{actual_orders_1m:calc(1),actual_orders_5m:calc(5),recent:this.liquidations.slice(-100)}}

  async pollDerivatives(){const jobs={
    Binance:async()=>{const[p,o,t]=await Promise.all([this._json('https://fapi.binance.com/fapi/v1/premiumIndex?symbol=BTCUSDT'),this._json('https://fapi.binance.com/fapi/v1/openInterest?symbol=BTCUSDT'),this._json('https://fapi.binance.com/fapi/v1/ticker/price?symbol=BTCUSDT')]);const price=num(t.price),oi=num(o.openInterest);return{status:'LIVE',observed_at:now(),price,oi_usd:price&&oi?price*oi:null,funding:num(p.lastFundingRate)}},
    Bybit:async()=>{const j=await this._json('https://api.bybit.com/v5/market/tickers?category=linear&symbol=BTCUSDT'),x=j.result?.list?.[0],price=num(x?.lastPrice),oi=num(x?.openInterestValue)??(price*num(x?.openInterest));return{status:'LIVE',observed_at:now(),price,oi_usd:oi,funding:num(x?.fundingRate)}},
    OKX:async()=>{const[o,f]=await Promise.all([this._json('https://www.okx.com/api/v5/public/open-interest?instType=SWAP&instId=BTC-USDT-SWAP'),this._json('https://www.okx.com/api/v5/public/funding-rate?instId=BTC-USDT-SWAP')]);return{status:'LIVE',observed_at:now(),price:num(f.data?.[0]?.markPx),oi_usd:num(o.data?.[0]?.oiUsd),funding:num(f.data?.[0]?.fundingRate)}}
  };const rs=await Promise.allSettled(Object.entries(jobs).map(async([k,fn])=>[k,await fn()]));for(const r of rs){if(r.status==='fulfilled')this.derivatives[r.value[0]]=r.value[1];else this.error(r.reason,'derivatives')}}
  composite(){const rows=[...this.books.values()].filter(x=>x.market_type==='spot'&&Date.now()-x.event_time_ms<5000);if(!rows.length)return null;const mids=rows.map(x=>({venue:x.venue,mid:(x.best_bid+x.best_ask)/2,spread:x.spread_bps})),sorted=mids.map(x=>x.mid).sort((a,b)=>a-b),med=sorted[Math.floor(sorted.length/2)],valid=mids.filter(x=>Math.abs(x.mid-med)/med<.005);let n=0,d=0;for(const x of valid){const w=1/Math.max(x.spread||2,.1);n+=x.mid*w;d+=w}const price=n/d;return{price,venue_count:valid.length,dispersion_bps:valid.length>1?(Math.max(...valid.map(x=>x.mid))-Math.min(...valid.map(x=>x.mid)))/price*10000:0,venues:valid}}
  core(){const c=this.composite();if(!c)return null;const spot={m1:this.flow.window('spot',1),m5:this.flow.window('spot',5),m15:this.flow.window('spot',15),m60:this.flow.window('spot',60)},perp={m1:this.flow.window('perp',1),m5:this.flow.window('perp',5),m15:this.flow.window('perp',15),m60:this.flow.window('perp',60)},live=Object.values(this.derivatives).filter(x=>x?.status==='LIVE'&&num(x.oi_usd)!==null),oi=live.length?live.reduce((a,x)=>a+Number(x.oi_usd),0):null,fr=live.filter(x=>num(x.funding)!==null),fund=fr.length?fr.reduce((a,x)=>a+Number(x.funding)*Number(x.oi_usd),0)/fr.reduce((a,x)=>a+Number(x.oi_usd),0):null,socketRows=Object.values(this.sockets),good=socketRows.filter(x=>x.status==='LIVE').length,bad=socketRows.filter(x=>['STALE','DISCONNECTED','PARTIAL'].includes(x.status)).length,quality=Math.max(15,Math.min(98,45+good*3-bad*5-this.clickhouseWriter.health().quarantined_batches*2));return{observed_at:now(),price:c.price,venue_count:c.venue_count,venue_dispersion_bps:c.dispersion_bps,spot,perp,open_interest_usd:oi,funding_oi_weighted:fund,actual_liquidations:this.liquidationState(),data_quality:quality,derivatives:structuredClone(this.derivatives),source_health:{sockets:structuredClone(this.sockets),redis:this.redisPublisher.health(),clickhouse:this.clickhouseWriter.health()}}}
  async start(){if(this.started)return;this.started=true;this._binance();this._bybit();await this._okx();this._coinbase();this._kraken();this._hyperliquid();this._deribit();this._bitfinex();this._gate();this._coinglassLiquidations();void this.pollDerivatives();this.derivTimer=setInterval(()=>void this.pollDerivatives(),Number(process.env.REST_POLL_MS||5000));this.derivTimer.unref?.()}
  stop(){clearInterval(this.derivTimer);for(const s of this.stoppers)s();this.stoppers=[];this.started=false}
}
