const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const now=()=>new Date().toISOString();
function parseExpiry(name){const p=String(name).split('-')[1];if(!p)return null;const m=p.match(/(\d{1,2})([A-Z]{3})(\d{2})/);if(!m)return null;const months={JAN:0,FEB:1,MAR:2,APR:3,MAY:4,JUN:5,JUL:6,AUG:7,SEP:8,OCT:9,NOV:10,DEC:11};return Date.UTC(2000+Number(m[3]),months[m[2]],Number(m[1]),8,0,0)}
async function get(url,headers={}){const c=new AbortController(),tm=setTimeout(()=>c.abort(),9000);try{const r=await fetch(url,{headers:{accept:'application/json',...headers},signal:c.signal});const t=await r.text();let j;try{j=JSON.parse(t)}catch{j={raw:t}}if(!r.ok)throw new Error(`${r.status} ${t.slice(0,160)}`);return j}finally{clearTimeout(tm)}}
async function cg(path,params={}){const key=process.env.COINGLASS_API_KEY;if(!key)throw new Error('COINGLASS_API_KEY missing');const q=new URLSearchParams(Object.entries(params).map(([k,v])=>[k,String(v)]));const j=await get(`https://open-api-v4.coinglass.com${path}?${q}`,{'CG-API-KEY':key});if(String(j.code)!=='0')throw new Error(j.msg||j.code);return j.data}
export async function collectOptionsV4(){const started=Date.now();try{
  const [sumR,dvolR,infoR,maxPainR,oiHistR,volHistR]=await Promise.allSettled([
    get('https://www.deribit.com/api/v2/public/get_book_summary_by_currency?currency=BTC&kind=option'),
    get(`https://www.deribit.com/api/v2/public/get_volatility_index_data?currency=BTC&start_timestamp=${Date.now()-24*60*60e3}&end_timestamp=${Date.now()}&resolution=60`),
    cg('/api/option/info',{symbol:'BTC'}),cg('/api/option/max-pain',{symbol:'BTC',exchange:'Deribit'}),cg('/api/option/exchange-oi-history',{symbol:'BTC',unit:'USD',range:'12h'}),cg('/api/option/exchange-vol-history',{symbol:'BTC',unit:'USD',range:'12h'})
  ]);
  const val=r=>r.status==='fulfilled'?r.value:null,summary=val(sumR)?.result||[],dv=val(dvolR)?.result?.data||[],dvol=dv.length?num(dv.at(-1)?.[4]):null;
  const rows=summary.map(o=>{const name=String(o.instrument_name||''),p=name.split('-'),strike=num(p.at(-2)),type=p.at(-1)==='C'?'call':p.at(-1)==='P'?'put':null,expiry=parseExpiry(name);return{name,strike,type,expiry,expiry_iso:expiry?new Date(expiry).toISOString():null,oi:num(o.open_interest),volume_usd:num(o.volume_usd),mark_iv:num(o.mark_iv),underlying:num(o.underlying_price),bid:num(o.bid_price),ask:num(o.ask_price)}}).filter(x=>x.type&&x.expiry&&x.strike);
  const expiries=new Map();for(const x of rows){const k=x.expiry_iso;let e=expiries.get(k);if(!e){e={expiry:k,expiry_ms:x.expiry,underlying:x.underlying,rows:[]};expiries.set(k,e)}e.rows.push(x)}
  const term=[];for(const e of expiries.values()){
    const u=num(e.underlying)||num(e.rows.find(x=>x.underlying)?.underlying);if(!u)continue;const days=Math.max((e.expiry_ms-Date.now())/86400000,0),atm=e.rows.filter(x=>x.mark_iv!==null).sort((a,b)=>Math.abs(a.strike-u)-Math.abs(b.strike-u)).slice(0,4),atmIv=atm.length?atm.reduce((a,x)=>a+x.mark_iv,0)/atm.length:null;
    const targetPut=u*.95,targetCall=u*1.05,put=e.rows.filter(x=>x.type==='put'&&x.mark_iv!==null).sort((a,b)=>Math.abs(a.strike-targetPut)-Math.abs(b.strike-targetPut))[0],call=e.rows.filter(x=>x.type==='call'&&x.mark_iv!==null).sort((a,b)=>Math.abs(a.strike-targetCall)-Math.abs(b.strike-targetCall))[0];
    const callIv=num(call?.mark_iv),putIv=num(put?.mark_iv),rr=callIv!==null&&putIv!==null?callIv-putIv:null,expected=atmIv!==null?u*(atmIv/100)*Math.sqrt(Math.max(days,1/24)/365):null;
    term.push({expiry:e.expiry,days_to_expiry:days,underlying:u,atm_iv:atmIv,expected_move_usd_1sd:expected,expected_move_pct:expected/u*100,skew_proxy:{method:'~5% OTM call IV minus ~5% OTM put IV; not 25-delta RR',call_strike:call?.strike,call_iv:callIv,put_strike:put?.strike,put_iv:putIv,risk_reversal_proxy:rr},open_interest:e.rows.reduce((a,x)=>a+(x.oi||0),0),volume_usd:e.rows.reduce((a,x)=>a+(x.volume_usd||0),0)});
  }term.sort((a,b)=>a.days_to_expiry-b.days_to_expiry);
  const calls=rows.filter(x=>x.type==='call'),puts=rows.filter(x=>x.type==='put'),callOi=calls.reduce((a,x)=>a+(x.oi||0),0),putOi=puts.reduce((a,x)=>a+(x.oi||0),0),callVol=calls.reduce((a,x)=>a+(x.volume_usd||0),0),putVol=puts.reduce((a,x)=>a+(x.volume_usd||0),0),info=val(infoR)||[];
  return{source:'options_v4',status:rows.length?'LIVE':'PARTIAL',observed_at:now(),latency_ms:Date.now()-started,dvol,atm_iv:term[0]?.atm_iv??null,term_structure:term.slice(0,24),expected_move:term.slice(0,12).map(x=>({expiry:x.expiry,days:x.days_to_expiry,usd_1sd:x.expected_move_usd_1sd,pct_1sd:x.expected_move_pct})),skew:term.slice(0,12).map(x=>({expiry:x.expiry,...x.skew_proxy})),put_call_oi_ratio:callOi?putOi/callOi:null,put_call_volume_ratio:callVol?putVol/callVol:null,option_oi:callOi+putOi,exchange_market_share:info,max_pain:val(maxPainR)||[],exchange_oi_history:val(oiHistR)||null,exchange_volume_history:val(volHistR)||null,gamma_context:{status:'UNAVAILABLE',reason:'True gamma exposure requires per-instrument greeks/dealer-position assumptions; the engine refuses to infer dealer gamma from OI alone.'},integrity:{skew:'Proxy by moneyness because public summary does not expose 25-delta greeks.',max_pain:'Supplementary only; never a primary directional signal.'}}
}catch(e){return{source:'options_v4',status:'UNAVAILABLE',observed_at:now(),error:String(e)}}}
