import WebSocket from 'ws';
import { createClient as createClickHouseClient } from '@clickhouse/client';
import { createClient as createSupabaseClient } from '@supabase/supabase-js';
import Fastify from 'fastify';
import pino from 'pino';
import { BybitBookReconstructor } from './bybit-book.js';
import { ClickHouseWriter } from './clickhouse-writer.js';
import { createBoundedRedis, FlowAccumulator, RedisPublisher } from './redis-state.js';
import { ExternalIntelligenceHub } from './external-intelligence.js';
import { SignalEngine } from './signal-engine.js';
import { SIGNAL_FAMILIES, REQUIRED_SOURCE_GROUPS } from './coverage.js';

const log = pino({ level: process.env.LOG_LEVEL || 'info' });
const fastify = Fastify({ logger:false });
const redis = createBoundedRedis(process.env.REDIS_URL);
const redisPublisher = new RedisPublisher(redis,{bookPublishIntervalMs:Number(process.env.REDIS_BOOK_PUBLISH_MS||200)});
const clickhouse = createClickHouseClient({url:process.env.CLICKHOUSE_URL,username:process.env.CLICKHOUSE_USER||'default',password:process.env.CLICKHOUSE_PASSWORD||'',database:process.env.CLICKHOUSE_DB||'btc',request_timeout:Number(process.env.CLICKHOUSE_REQUEST_TIMEOUT_MS||10000)});
const clickhouseWriter = new ClickHouseWriter(clickhouse,{maxTradeBuffer:Number(process.env.MAX_TRADE_BUFFER||100000),maxBookBuffer:Number(process.env.MAX_BOOK_BUFFER||20000),maxQuarantineBatches:Number(process.env.MAX_QUARANTINE_BATCHES||200)});
const supabase = process.env.SUPABASE_URL&&process.env.SUPABASE_SERVICE_ROLE_KEY?createSupabaseClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false}}):null;
const flow = new FlowAccumulator({retentionMinutes:Number(process.env.FLOW_RETENTION_MINUTES||240)});
const signalEngine = new SignalEngine();
const localBooks=new Map(),lastBookSample=new Map(),derivativeState={};
const BOOK_SAMPLE_MS=Number(process.env.BOOK_SAMPLE_MS||1000),STATE_INTERVAL_MS=Number(process.env.STATE_INTERVAL_MS||1000),REST_POLL_MS=Number(process.env.REST_POLL_MS||5000),SUPABASE_INTERVAL_MS=Number(process.env.SUPABASE_INTERVAL_MS||15000);
const state={startedAt:new Date().toISOString(),sockets:{},current:null,external:{},intelligence:null,errors:[],lastSupabaseAt:null,lastAlertKey:null,lastSetupKey:null};
const externalHub=new ExternalIntelligenceHub({getPrice:()=>state.current?.price});
let okxSwapCtVal=null;

const num=v=>{if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)?n:null};
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
function addError(err,context){const x={at:new Date().toISOString(),context,error:String(err)};state.errors.push(x);if(state.errors.length>100)state.errors.shift();log.warn(x)}
function socketHealth(name,patch){state.sockets[name]={...(state.sockets[name]||{}),...patch}}

function pushTrade({venue,market_type,symbol,price,qty,side,event_time_ms,trade_id=null,notional_usd=null}){
  const p=num(price),q=num(qty),t=num(event_time_ms);if(!p||!q||!t||!['buy','sell'].includes(side))return;
  const row={event_time:new Date(t).toISOString(),ingested_at:new Date().toISOString(),event_time_ms:t,venue,market_type,symbol,price:p,qty:q,notional_usd:num(notional_usd)??p*q,side,trade_id:String(trade_id??'')};
  flow.recordTrade(row);clickhouseWriter.enqueueTrade(row);
}
function pushBook({venue,market_type,symbol,event_time_ms,bids,asks,sequence=null}){
  if(!Array.isArray(bids)||!Array.isArray(asks)||!bids.length||!asks.length)return;
  const normalize=x=>Array.isArray(x)?[x[0],x[1]]:[x.price??x.px,x.qty??x.size??x.sz];
  bids=bids.map(normalize).filter(x=>num(x[0])&&num(x[1])).sort((a,b)=>Number(b[0])-Number(a[0]));
  asks=asks.map(normalize).filter(x=>num(x[0])&&num(x[1])).sort((a,b)=>Number(a[0])-Number(b[0]));
  if(!bids.length||!asks.length)return;const bestBid=num(bids[0][0]),bestAsk=num(asks[0][0]);if(!bestBid||!bestAsk||bestAsk<=bestBid)return;
  const mid=(bestBid+bestAsk)/2,spreadBps=(bestAsk-bestBid)/mid*10000,t=num(event_time_ms)||Date.now();
  const row={event_time:new Date(t).toISOString(),ingested_at:new Date().toISOString(),event_time_ms:t,venue,market_type,symbol,sequence:String(sequence??''),bid_prices:bids.slice(0,50).map(x=>Number(x[0])),bid_sizes:bids.slice(0,50).map(x=>Number(x[1])),ask_prices:asks.slice(0,50).map(x=>Number(x[0])),ask_sizes:asks.slice(0,50).map(x=>Number(x[1])),best_bid:bestBid,best_ask:bestAsk,spread_bps:spreadBps};
  const key=`${venue}:${market_type}`;localBooks.set(key,row);void redisPublisher.publishBook(row);const last=lastBookSample.get(key)||0;if(Date.now()-last>=BOOK_SAMPLE_MS){lastBookSample.set(key,Date.now());clickhouseWriter.enqueueBook(row)}
}

function connectSocket(name,url,{onOpen,onMessage,onReset,appPing=null,parse=(b)=>JSON.parse(b.toString())}={}){
  let ws,closed=false,attempt=0,pingTimer,watchdog;const start=()=>{if(closed)return;attempt++;socketHealth(name,{status:'CONNECTING',attempt,url});onReset?.();ws=new WebSocket(url);
    ws.on('open',()=>{attempt=0;socketHealth(name,{status:'LIVE',connected_at:new Date().toISOString(),last_message_at:null});try{onOpen?.(ws)}catch(e){addError(e,`${name}:open`)}pingTimer=setInterval(()=>{try{if(ws.readyState!==WebSocket.OPEN)return;if(appPing)ws.send(typeof appPing==='string'?appPing:JSON.stringify(appPing));else ws.ping()}catch(e){addError(e,`${name}:ping`)}},20000);watchdog=setInterval(()=>{const h=state.sockets[name],last=h?.last_message_at?Date.parse(h.last_message_at):0;if(last&&Date.now()-last>45000){socketHealth(name,{status:'STALE'});try{ws.terminate()}catch{}}},10000)});
    ws.on('message',buf=>{socketHealth(name,{status:'LIVE',last_message_at:new Date().toISOString()});try{onMessage?.(parse(buf),ws)}catch(e){addError(e,`${name}:message`)}});ws.on('error',e=>addError(e,`${name}:socket`));ws.on('close',()=>{clearInterval(pingTimer);clearInterval(watchdog);onReset?.();socketHealth(name,{status:'DISCONNECTED',disconnected_at:new Date().toISOString()});setTimeout(start,Math.min(30000,1000*2**Math.min(attempt,5)))})};start();return()=>{closed=true;clearInterval(pingTimer);clearInterval(watchdog);onReset?.();try{ws?.close()}catch{}};
}

// Binance: primary liquid spot + perpetual feed.
connectSocket('binance_spot','wss://stream.binance.com:9443/stream?streams=btcusdt@aggTrade/btcusdt@depth20@100ms',{onMessage:m=>{const d=m.data||m;if(m.stream?.includes('aggTrade'))pushTrade({venue:'Binance',market_type:'spot',symbol:'BTCUSDT',price:d.p,qty:d.q,side:d.m?'sell':'buy',event_time_ms:d.T,trade_id:d.a});else if(m.stream?.includes('depth'))pushBook({venue:'Binance',market_type:'spot',symbol:'BTCUSDT',event_time_ms:d.E||Date.now(),bids:d.bids||d.b||[],asks:d.asks||d.a||[],sequence:d.lastUpdateId||d.u})}});
connectSocket('binance_perp','wss://fstream.binance.com/stream?streams=btcusdt@aggTrade/btcusdt@depth20@100ms',{onMessage:m=>{const d=m.data||m;if(m.stream?.includes('aggTrade'))pushTrade({venue:'Binance',market_type:'perp',symbol:'BTCUSDT-PERP',price:d.p,qty:d.q,side:d.m?'sell':'buy',event_time_ms:d.T,trade_id:d.a});else if(m.stream?.includes('depth'))pushBook({venue:'Binance',market_type:'perp',symbol:'BTCUSDT-PERP',event_time_ms:d.E||Date.now(),bids:d.b||[],asks:d.a||[],sequence:d.u})}});

// Bybit: snapshot + delta order-book reconstruction.
function bybit(category,marketType){const recon=new BybitBookReconstructor({depth:50});connectSocket(`bybit_${marketType}`,`wss://stream.bybit.com/v5/public/${category}`,{appPing:{op:'ping'},onReset:()=>recon.reset(),onOpen:ws=>ws.send(JSON.stringify({op:'subscribe',args:['publicTrade.BTCUSDT','orderbook.50.BTCUSDT']})),onMessage:m=>{if(m.topic==='publicTrade.BTCUSDT')for(const t of m.data||[])pushTrade({venue:'Bybit',market_type:marketType,symbol:marketType==='spot'?'BTCUSDT':'BTCUSDT-PERP',price:t.p,qty:t.v,side:String(t.S).toLowerCase()==='buy'?'buy':'sell',event_time_ms:t.T||m.ts,trade_id:t.i});if(m.topic==='orderbook.50.BTCUSDT'){const a=recon.applyMessage(m);if(!a.book){if(a.status==='WAITING_SNAPSHOT')socketHealth(`bybit_${marketType}`,{status:'PARTIAL',book_status:a.status});return}pushBook({venue:'Bybit',market_type:marketType,symbol:marketType==='spot'?'BTCUSDT':'BTCUSDT-PERP',event_time_ms:m.cts||m.ts||Date.now(),bids:a.book.bids,asks:a.book.asks,sequence:a.book.seq})}}})}bybit('spot','spot');bybit('linear','perp');

// OKX: spot + swap. Swap contracts are normalized from instrument metadata.
async function loadOkxContract(){try{const r=await fetch('https://www.okx.com/api/v5/public/instruments?instType=SWAP&instId=BTC-USDT-SWAP');const j=await r.json();okxSwapCtVal=num(j.data?.[0]?.ctVal);socketHealth('okx_perp',{contract_value_btc:okxSwapCtVal})}catch(e){addError(e,'okx:contract')}}void loadOkxContract();setInterval(()=>void loadOkxContract(),3600000).unref();
function okx(instId,marketType){connectSocket(`okx_${marketType}`,'wss://ws.okx.com:8443/ws/v5/public',{appPing:'ping',onOpen:ws=>ws.send(JSON.stringify({op:'subscribe',args:[{channel:'trades',instId},{channel:'books5',instId}]})),onMessage:m=>{if(m.arg?.channel==='trades')for(const t of m.data||[]){let q=num(t.sz);if(marketType==='perp'){if(!okxSwapCtVal)return;q*=okxSwapCtVal}pushTrade({venue:'OKX',market_type:marketType,symbol:instId,price:t.px,qty:q,side:t.side,event_time_ms:t.ts,trade_id:t.tradeId})}if(m.arg?.channel==='books5')for(const b of m.data||[])pushBook({venue:'OKX',market_type:marketType,symbol:instId,event_time_ms:b.ts||Date.now(),bids:b.bids||[],asks:b.asks||[],sequence:b.seqId})}})}okx('BTC-USDT','spot');okx('BTC-USDT-SWAP','perp');

// Coinbase Advanced Trade public market data.
connectSocket('coinbase_spot','wss://advanced-trade-ws.coinbase.com',{onOpen:ws=>{for(const channel of ['market_trades','level2'])ws.send(JSON.stringify({type:'subscribe',product_ids:['BTC-USD'],channel}))},onMessage:m=>{for(const e of m.events||[]){if(e.type==='update'&&Array.isArray(e.trades))for(const t of e.trades)pushTrade({venue:'Coinbase',market_type:'spot',symbol:'BTC-USD',price:t.price,qty:t.size,side:String(t.side).toUpperCase()==='BUY'?'buy':'sell',event_time_ms:Date.parse(t.time)||Date.now(),trade_id:t.trade_id});if(Array.isArray(e.updates)){const bids=[],asks=[];for(const u of e.updates){const row=[u.price_level,u.new_quantity];if(String(u.side).toLowerCase()==='bid')bids.push(row);else asks.push(row)}const old=localBooks.get('Coinbase:spot');if(old){const merge=(prices,sizes,updates,desc)=>{const mp=new Map(prices.map((p,i)=>[Number(p),Number(sizes[i])]));for(const [p,q] of updates){const pn=Number(p),qn=Number(q);if(qn===0)mp.delete(pn);else mp.set(pn,qn)}return [...mp.entries()].sort((a,b)=>desc?b[0]-a[0]:a[0]-b[0]).slice(0,50)};const bb=merge(old.bid_prices,old.bid_sizes,bids,true),aa=merge(old.ask_prices,old.ask_sizes,asks,false);if(bb.length&&aa.length)pushBook({venue:'Coinbase',market_type:'spot',symbol:'BTC-USD',event_time_ms:Date.now(),bids:bb,asks:aa})}}}}});

// Kraken v2 public trades/order book.
connectSocket('kraken_spot','wss://ws.kraken.com/v2',{onOpen:ws=>{ws.send(JSON.stringify({method:'subscribe',params:{channel:'trade',symbol:['BTC/USD'],snapshot:false}}));ws.send(JSON.stringify({method:'subscribe',params:{channel:'book',symbol:['BTC/USD'],depth:25,snapshot:true}}))},onMessage:m=>{if(m.channel==='trade')for(const t of m.data||[])pushTrade({venue:'Kraken',market_type:'spot',symbol:'BTC/USD',price:t.price,qty:t.qty,side:t.side==='buy'?'buy':'sell',event_time_ms:Date.parse(t.timestamp)||Date.now(),trade_id:t.trade_id});if(m.channel==='book')for(const b of m.data||[]){const bids=b.bids||b.bid||[],asks=b.asks||b.ask||[];if(bids.length&&asks.length)pushBook({venue:'Kraken',market_type:'spot',symbol:'BTC/USD',event_time_ms:Date.parse(b.timestamp)||Date.now(),bids,asks,sequence:b.checksum})}}});

// Hyperliquid public BTC perpetual flow + L2 book.
connectSocket('hyperliquid_perp','wss://api.hyperliquid.xyz/ws',{onOpen:ws=>{ws.send(JSON.stringify({method:'subscribe',subscription:{type:'trades',coin:'BTC'}}));ws.send(JSON.stringify({method:'subscribe',subscription:{type:'l2Book',coin:'BTC'}}))},onMessage:m=>{if(m.channel==='trades')for(const t of m.data||[])pushTrade({venue:'Hyperliquid',market_type:'perp',symbol:'BTC-PERP',price:t.px,qty:t.sz,side:t.side==='B'?'buy':'sell',event_time_ms:t.time||Date.now(),trade_id:t.hash});if(m.channel==='l2Book'){const levels=m.data?.levels||[];if(levels[0]?.length&&levels[1]?.length)pushBook({venue:'Hyperliquid',market_type:'perp',symbol:'BTC-PERP',event_time_ms:m.data?.time||Date.now(),bids:levels[0],asks:levels[1]})}}});

// Deribit BTC perpetual. Option analytics are handled in ExternalIntelligenceHub.
connectSocket('deribit_perp','wss://www.deribit.com/ws/api/v2',{onOpen:ws=>ws.send(JSON.stringify({jsonrpc:'2.0',id:1,method:'public/subscribe',params:{channels:['trades.BTC-PERPETUAL.100ms','book.BTC-PERPETUAL.100ms']}})),onMessage:m=>{if(m.method!=='subscription')return;const ch=m.params?.channel||'',d=m.params?.data;if(ch.startsWith('trades.'))for(const t of d||[]){const usd=num(t.amount);const p=num(t.price);if(!usd||!p)continue;pushTrade({venue:'Deribit',market_type:'perp',symbol:'BTC-PERPETUAL',price:p,qty:usd/p,notional_usd:usd,side:t.direction==='buy'?'buy':'sell',event_time_ms:t.timestamp,trade_id:t.trade_id})}if(ch.startsWith('book.')&&d?.bids?.length&&d?.asks?.length)pushBook({venue:'Deribit',market_type:'perp',symbol:'BTC-PERPETUAL',event_time_ms:d.timestamp||Date.now(),bids:d.bids,asks:d.asks,sequence:d.change_id})}});

async function fetchJson(url){const c=new AbortController(),timer=setTimeout(()=>c.abort(),3500);try{const r=await fetch(url,{headers:{accept:'application/json'},signal:c.signal});if(!r.ok)throw new Error(`${r.status} ${url}`);return await r.json()}finally{clearTimeout(timer)}}
async function fetchBinanceDerivatives(){const[premium,oi,ticker]=await Promise.all([fetchJson('https://fapi.binance.com/fapi/v1/premiumIndex?symbol=BTCUSDT'),fetchJson('https://fapi.binance.com/fapi/v1/openInterest?symbol=BTCUSDT'),fetchJson('https://fapi.binance.com/fapi/v1/ticker/price?symbol=BTCUSDT')]);const price=num(ticker.price),contracts=num(oi.openInterest);return{status:'LIVE',observed_at:new Date().toISOString(),price,oi_usd:price&&contracts?price*contracts:null,funding:num(premium.lastFundingRate),source_event_at:num(premium.time)||Date.now()}}
async function fetchBybitDerivatives(){const p=(await fetchJson('https://api.bybit.com/v5/market/tickers?category=linear&symbol=BTCUSDT')).result?.list?.[0];const price=num(p?.lastPrice),oiBase=num(p?.openInterest),oiValue=num(p?.openInterestValue);return{status:'LIVE',observed_at:new Date().toISOString(),price,oi_usd:oiValue??(price&&oiBase?price*oiBase:null),funding:num(p?.fundingRate),source_event_at:Date.now()}}
async function fetchOkxDerivatives(){const[oi,funding]=await Promise.all([fetchJson('https://www.okx.com/api/v5/public/open-interest?instType=SWAP&instId=BTC-USDT-SWAP'),fetchJson('https://www.okx.com/api/v5/public/funding-rate?instId=BTC-USDT-SWAP')]);const o=oi.data?.[0],f=funding.data?.[0];return{status:'LIVE',observed_at:new Date().toISOString(),price:num(f?.markPx),oi_usd:num(o?.oiUsd),funding:num(f?.fundingRate),source_event_at:num(f?.ts)||Date.now()}}
async function pollDerivatives(){const venues=[['Binance',fetchBinanceDerivatives],['Bybit',fetchBybitDerivatives],['OKX',fetchOkxDerivatives]],rs=await Promise.allSettled(venues.map(([,fn])=>fn()));for(let i=0;i<rs.length;i++){const[venue]=venues[i],r=rs[i];if(r.status==='fulfilled')derivativeState[venue]=r.value;else{const old=derivativeState[venue];derivativeState[venue]=old?{...old,status:'STALE',error:String(r.reason),failed_at:new Date().toISOString()}:{status:'UNAVAILABLE',oi_usd:null,funding:null,error:String(r.reason)};addError(r.reason,`derivatives:${venue}`)}}void redisPublisher.publishDerivatives(derivativeState)}

function computeComposite(){const books=[...localBooks.values()].filter(x=>x.market_type==='spot'&&x.best_bid&&x.best_ask&&Date.now()-x.event_time_ms<5000);if(!books.length)return null;const mids=books.map(x=>({venue:x.venue,mid:(x.best_bid+x.best_ask)/2,spread_bps:x.spread_bps}));const sorted=mids.map(x=>x.mid).sort((a,b)=>a-b),median=sorted[Math.floor(sorted.length/2)],valid=mids.filter(x=>Math.abs(x.mid-median)/median<.005);let n=0,d=0;for(const x of valid){const w=1/Math.max(Number(x.spread_bps||2),.1);n+=x.mid*w;d+=w}const price=n/d,dispersion_bps=valid.length>1?(Math.max(...valid.map(x=>x.mid))-Math.min(...valid.map(x=>x.mid)))/price*10000:0;return{price,venue_count:valid.length,dispersion_bps,venues:valid}}
function buildCore(){const c=computeComposite();if(!c)return null;const spot={m1:flow.window('spot',1),m5:flow.window('spot',5),m15:flow.window('spot',15),m60:flow.window('spot',60)},perp={m1:flow.window('perp',1),m5:flow.window('perp',5),m15:flow.window('perp',15),m60:flow.window('perp',60)};const live=Object.values(derivativeState).filter(v=>v?.status==='LIVE'&&v.oi_usd!==null),oi=live.length?live.reduce((a,v)=>a+Number(v.oi_usd),0):null,fr=live.filter(v=>v.funding!==null),fw=fr.length?fr.reduce((a,v)=>a+Number(v.funding)*Number(v.oi_usd),0)/fr.reduce((a,v)=>a+Number(v.oi_usd),0):null;const sockets=Object.values(state.sockets),good=sockets.filter(x=>x.status==='LIVE').length,bad=sockets.filter(x=>['STALE','DISCONNECTED','PARTIAL'].includes(x.status)).length,q=clamp(45+good*3-bad*5-clickhouseWriter.health().quarantined_batches*2,15,98);return{observed_at:new Date().toISOString(),price:c.price,venue_count:c.venue_count,venue_dispersion_bps:c.dispersion_bps,spot,perp,open_interest_usd:oi,funding_oi_weighted:fw,data_quality:q,derivatives:structuredClone(derivativeState),source_health:{sockets:state.sockets,redis:redisPublisher.health(),clickhouse:clickhouseWriter.health()}}}
async function publishState(){try{const core=buildCore();if(!core)return;state.external=externalHub.snapshot();state.intelligence=signalEngine.evaluate(core,state.external);state.current={...core,external:state.external,intelligence:state.intelligence,engine_version:'railway-v3-single-authority'};await redisPublisher.publishState(state.current)}catch(e){addError(e,'publishState')}}

async function persistSupabase(){if(!supabase||!state.current)return;const s=state.current,i=s.intelligence||{},cg=s.external?.coinglass||{};try{const row={observed_at:s.observed_at,composite_price_usd:s.price,composite_method:'Railway v3 direct-WebSocket composite; CoinGlass broad-venue reconciliation',venue_count:s.venue_count,venue_dispersion_bps:s.venue_dispersion_bps,spot_cvd_usd_1m:num(cg?.flow?.spot_cvd_1m)??s.spot.m1.delta_usd,spot_cvd_usd_5m:num(cg?.flow?.spot_cvd_5m)??s.spot.m5.delta_usd,spot_cvd_usd_15m:num(cg?.flow?.spot_cvd_15m)??s.spot.m15.delta_usd,spot_cvd_usd_1h:num(cg?.flow?.spot_cvd_1h)??s.spot.m60.delta_usd,perp_cvd_usd_1m:num(cg?.flow?.perp_cvd_1m)??s.perp.m1.delta_usd,perp_cvd_usd_5m:num(cg?.flow?.perp_cvd_5m)??s.perp.m5.delta_usd,perp_cvd_usd_15m:num(cg?.flow?.perp_cvd_15m)??s.perp.m15.delta_usd,perp_cvd_usd_1h:num(cg?.flow?.perp_cvd_1h)??s.perp.m60.delta_usd,open_interest_usd:num(cg?.open_interest?.total_usd)??s.open_interest_usd,funding_oi_weighted:num(cg?.funding?.oi_weighted)??s.funding_oi_weighted,funding_volume_weighted:num(cg?.funding?.volume_weighted),long_liquidations_usd_1m:num(cg?.liquidations?.long_1m_usd),short_liquidations_usd_1m:num(cg?.liquidations?.short_1m_usd),long_liquidations_usd_5m:num(cg?.liquidations?.long_5m_usd),short_liquidations_usd_5m:num(cg?.liquidations?.short_5m_usd),liquidation_velocity_usd_per_min:num(cg?.liquidations?.velocity_usd_per_min),nearest_liquidity_above_usd:num(cg?.liquidations?.map?.above?.price),nearest_liquidity_below_usd:num(cg?.liquidations?.map?.below?.price),nearest_liquidity_above_notional_usd:num(cg?.liquidations?.map?.above?.notional_usd),nearest_liquidity_below_notional_usd:num(cg?.liquidations?.map?.below?.notional_usd),driver_classification:i.driver_classification||'UNCLEAR',driver_confidence:i.regime_confidence||0,data_quality:i.data_quality??s.data_quality,freshness:Object.fromEntries(Object.entries(s.external||{}).map(([k,v])=>[k,{status:v?.status,age_ms:v?.age_ms??null}])),source_health:s.source_health,raw:{engine:'railway-v3-single-authority',external:s.external}};const{error}=await supabase.from('btc_market_snapshots').insert(row);if(error)throw error;
    const signalRow={singleton:true,updated_at:i.updated_at,primary_regime:i.primary_regime,secondary_regime:i.secondary_regime,regime_confidence:i.regime_confidence,bull_score:i.bull_score,bear_score:i.bear_score,trade_confidence:i.trade_confidence,event_risk:i.event_risk,preferred_action:i.preferred_action,active_setup:i.active_setup||{},watchlist:i.watchlist||[],explainability:i.explainability||{}};const{error:se}=await supabase.from('btc_signal_state').upsert(signalRow,{onConflict:'singleton'});if(se)throw se;
    const{error:fe}=await supabase.from('btc_feature_snapshots').insert({observed_at:s.observed_at,engine_version:'railway-v3-single-authority',price_usd:s.price,structure:i.structure||{},external:s.external||{},signal:i||{},coverage:{signal_families:SIGNAL_FAMILIES,required_source_groups:REQUIRED_SOURCE_GROUPS}});if(fe&&String(fe.message||'').includes('btc_feature_snapshots')===false)throw fe;
    if(i.active_setup){const key=JSON.stringify([i.active_setup.setup_type,i.active_setup.direction,Math.round(i.active_setup.stop_risk_level||0)]);if(key!==state.lastSetupKey){state.lastSetupKey=key;await supabase.from('btc_setups').insert({status:'WATCH',setup_type:i.active_setup.setup_type,direction:i.active_setup.direction,time_horizon:'intraday',confidence:i.trade_confidence,data_quality:i.data_quality,entry_zone:i.active_setup.entry_zone,trigger_required:i.active_setup.trigger_required,invalidation:i.active_setup.invalidation,stop_risk_level:i.active_setup.stop_risk_level,targets:i.active_setup.targets,expected_rr:i.active_setup.expected_rr,key_levels:i.active_setup.liquidity_context,evidence:{confirmations:i.active_setup.confirmations,driver:i.active_setup.driver},contradictions:i.active_setup.contradictions,cancel_conditions:[i.active_setup.invalidation],expires_at:i.active_setup.expires_at})}}
    if(i.priority&&i.priority!=='INFO'){const key=`${i.priority}:${i.preferred_action}:${i.driver_classification}:${Math.round(i.trade_confidence||0)/5}`;if(key!==state.lastAlertKey){state.lastAlertKey=key;await supabase.from('btc_alerts').insert({priority:i.priority,alert_type:i.active_setup?'SETUP_WATCH':'REGIME_WATCH',dedupe_key:`${key}:${new Date().toISOString().slice(0,13)}`,title:`BTC ${i.priority} — ${i.preferred_action}`,payload:{price:s.price,intelligence:i}})}}
    state.lastSupabaseAt=new Date().toISOString();
  }catch(e){addError(e,'persistSupabase')}}

setInterval(()=>void clickhouseWriter.flushTrades().catch(e=>addError(e,'clickhouse:trades')),750).unref();setInterval(()=>void clickhouseWriter.flushBooks().catch(e=>addError(e,'clickhouse:books')),1000).unref();setInterval(()=>void pollDerivatives(),REST_POLL_MS).unref();setInterval(()=>void publishState(),STATE_INTERVAL_MS).unref();setInterval(()=>void persistSupabase(),SUPABASE_INTERVAL_MS).unref();void pollDerivatives();externalHub.start();void publishState();

fastify.get('/health',async()=>({ok:true,engine:'railway-v3-single-authority',now:new Date().toISOString(),started_at:state.startedAt,redis:redisPublisher.health(),clickhouse:clickhouseWriter.health(),sockets:state.sockets,external:Object.fromEntries(Object.entries(state.external||{}).map(([k,v])=>[k,{status:v?.status,age_ms:v?.age_ms,error:v?.error}])),last_state_at:state.current?.observed_at||null,last_supabase_at:state.lastSupabaseAt,errors:state.errors.slice(-15)}));
fastify.get('/state',async()=>state.current||{ok:false,status:'WARMING_UP'});
fastify.get('/intelligence',async()=>({ok:!!state.current,engine:'railway-v3-single-authority',market:state.current,intelligence:state.intelligence,coverage:{signal_families:SIGNAL_FAMILIES,required_source_groups:REQUIRED_SOURCE_GROUPS}}));
const port=Number(process.env.PORT||3000);fastify.listen({port,host:'0.0.0.0'}).then(()=>log.info({port},'BTC Global Intelligence v3 running')).catch(e=>{log.fatal(e);process.exit(1)});
for(const sig of ['SIGTERM','SIGINT'])process.on(sig,async()=>{log.info({sig},'shutting down');externalHub.stop();await clickhouseWriter.flushAll();try{await redis.quit()}catch{}try{await clickhouse.close()}catch{}process.exit(0)});
