import { createClient as createClickHouseClient } from '@clickhouse/client';
import { createClient as createSupabaseClient } from '@supabase/supabase-js';
import Fastify from 'fastify';
import pino from 'pino';
import { createBoundedRedis, FlowAccumulator, RedisPublisher } from './redis-state.js';
import { ClickHouseWriter } from './clickhouse-writer.js';
import { DirectMarketHub } from './direct-market.js';
import { StructureEngine } from './structure-engine.js';
import { ExternalV4Hub } from './external-v4.js';
import { MacroEventCalendar } from './event-calendar.js';
import { SignalEngine } from './signal-engine.js';
import { SIGNAL_FAMILIES, REQUIRED_SOURCE_GROUPS } from './coverage.js';

const log=pino({level:process.env.LOG_LEVEL||'info'}),app=Fastify({logger:false});
const redis=createBoundedRedis(process.env.REDIS_URL),redisPublisher=new RedisPublisher(redis,{bookPublishIntervalMs:Number(process.env.REDIS_BOOK_PUBLISH_MS||200)});
const clickhouse=createClickHouseClient({url:process.env.CLICKHOUSE_URL,username:process.env.CLICKHOUSE_USER||'default',password:process.env.CLICKHOUSE_PASSWORD||'',database:process.env.CLICKHOUSE_DB||'btc',request_timeout:Number(process.env.CLICKHOUSE_REQUEST_TIMEOUT_MS||10000)});
const clickhouseWriter=new ClickHouseWriter(clickhouse,{maxTradeBuffer:Number(process.env.MAX_TRADE_BUFFER||100000),maxBookBuffer:Number(process.env.MAX_BOOK_BUFFER||20000),maxQuarantineBatches:Number(process.env.MAX_QUARANTINE_BATCHES||200)});
const supabase=process.env.SUPABASE_URL&&process.env.SUPABASE_SERVICE_ROLE_KEY?createSupabaseClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false}}):null;
const flow=new FlowAccumulator({retentionMinutes:Number(process.env.FLOW_RETENTION_MINUTES||240)}),structure=new StructureEngine(),signalEngine=new SignalEngine();
const market=new DirectMarketHub({flow,clickhouseWriter,redisPublisher,structureEngine:structure,log,bookSampleMs:Number(process.env.BOOK_SAMPLE_MS||1000)}),external=new ExternalV4Hub({getPrice:()=>state.current?.price}),calendar=new MacroEventCalendar();
const state={started_at:new Date().toISOString(),current:null,errors:[],last_supabase_at:null,last_feature_at:null,last_setup_key:null,last_alert_key:null,last_external_persist:{}};
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null},now=()=>new Date().toISOString();
function err(e,context){const x={at:now(),context,error:String(e)};state.errors.push(x);if(state.errors.length>100)state.errors.shift();log.warn(x)}
function riskRank(x){return({LOW:0,MEDIUM:1,HIGH:2,EXTREME:3})[x]??0}function maxRisk(a,b){return riskRank(a)>=riskRank(b)?a:b}

function reconcile(core,ext){
  const cg=ext.coinglass||{},cgFlow=cg.flow||{},cgLiq=cg.liquidations||{},actual=core.actual_liquidations||{};
  return{...core,
    spot:{...core.spot,reconciled:{m1:num(cgFlow.spot_cvd_1m)??core.spot.m1.delta_usd,m5:num(cgFlow.spot_cvd_5m)??core.spot.m5.delta_usd,m15:num(cgFlow.spot_cvd_15m)??core.spot.m15.delta_usd,m60:num(cgFlow.spot_cvd_1h)??core.spot.m60.delta_usd,source:cg.status==='LIVE'?'CoinGlass all-exchange':'direct-WebSocket fallback'}},
    perp:{...core.perp,reconciled:{m1:num(cgFlow.perp_cvd_1m)??core.perp.m1.delta_usd,m5:num(cgFlow.perp_cvd_5m)??core.perp.m5.delta_usd,m15:num(cgFlow.perp_cvd_15m)??core.perp.m15.delta_usd,m60:num(cgFlow.perp_cvd_1h)??core.perp.m60.delta_usd,source:cg.status==='LIVE'?'CoinGlass all-exchange':'direct-WebSocket fallback'}},
    open_interest_usd:num(cg?.open_interest?.total_usd)??core.open_interest_usd,
    funding_oi_weighted:num(cg?.funding?.oi_weighted)??core.funding_oi_weighted,
    liquidation_state:{actual_orders:actual,aggregated_history:{long_1m_usd:num(cgLiq.long_1m_usd),short_1m_usd:num(cgLiq.short_1m_usd),long_5m_usd:num(cgLiq.long_5m_usd),short_5m_usd:num(cgLiq.short_5m_usd),velocity_usd_per_min:num(cgLiq.velocity_usd_per_min)},modelled_positioning:{map:cgLiq.map||null,heatmap:cgLiq.heatmap||null},integrity_note:'Actual forced-liquidation orders and modelled liquidation positioning are distinct and are never conflated.'},
    orderbook_aggregate:cg.orderbook||null,etf:cg.etf||null
  }
}
function evaluate(core,ext,eventCalendar){
  const adjusted={...core,spot:{...core.spot,m5:{...core.spot.m5,delta_usd:core.spot.reconciled?.m5??core.spot.m5.delta_usd}},perp:{...core.perp,m5:{...core.perp.m5,delta_usd:core.perp.reconciled?.m5??core.perp.m5.delta_usd}}};
  let i=signalEngine.evaluate(adjusted,ext);const calRisk=eventCalendar?.event_risk||'LOW';i.event_risk=maxRisk(i.event_risk||'LOW',calRisk);if(i.event_risk==='EXTREME'){i.trade_confidence=Math.min(Number(i.trade_confidence||0),45);if(i.active_setup){i.active_setup=null;i.watchlist=[];i.preferred_action='NO_TRADE';i.priority='HIGH';i.explainability={...(i.explainability||{}),event_gate:'Trade authorization suppressed because a CRITICAL/HIGH macro release is within the extreme event-risk window.'}}}return i
}
async function tick(){try{const raw=market.core();if(!raw)return;const ext=external.snapshot(),eventCalendar=calendar.snapshot();ext.event_calendar=eventCalendar;const core=reconcile(raw,ext),fullStructure=structure.snapshot(core.price),intelligence=evaluate(core,ext,eventCalendar);state.current={engine:'railway-v4-single-authority',observed_at:now(),...core,structure:fullStructure,external:ext,intelligence,coverage:{direct_websocket_venues:Object.keys(market.sockets),coinglass:ext.coinglass?.coverage||null,signal_families:SIGNAL_FAMILIES,required_source_groups:REQUIRED_SOURCE_GROUPS}};await redisPublisher.publishState(state.current)}catch(e){err(e,'tick')}}

async function persistClickHouseFeature(){if(!state.current)return;const s=state.current,i=s.intelligence||{},cg=s.external?.coinglass||{},liq=cg.liquidations||{};try{await clickhouse.insert({table:'intelligence_1m_v3',format:'JSONEachRow',values:[{minute:new Date(Math.floor(Date.now()/60000)*60000).toISOString().replace('T',' ').replace('Z',''),ingested_at:now(),price_usd:s.price,spot_cvd_1m:num(s.spot?.reconciled?.m1),spot_cvd_5m:num(s.spot?.reconciled?.m5),perp_cvd_1m:num(s.perp?.reconciled?.m1),perp_cvd_5m:num(s.perp?.reconciled?.m5),open_interest_usd:num(s.open_interest_usd),funding_oi_weighted:num(s.funding_oi_weighted),long_liq_5m_usd:num(liq.long_5m_usd),short_liq_5m_usd:num(liq.short_5m_usd),bull_score:num(i.bull_score),bear_score:num(i.bear_score),trade_confidence:num(i.trade_confidence),data_quality:num(i.data_quality),regime:String(i.primary_regime||'UNKNOWN'),driver:String(i.driver_classification||'UNCLEAR'),event_risk:String(i.event_risk||'LOW'),payload:JSON.stringify({structure:s.structure,external_health:Object.fromEntries(Object.entries(s.external||{}).map(([k,v])=>[k,{status:v?.status,age_ms:v?.age_ms??null}]))})}]});state.last_feature_at=now()}catch(e){err(e,'clickhouse:intelligence_1m')}}

async function insert(table,row){if(!supabase)return false;const{error}=await supabase.from(table).insert(row);if(error)throw error;return true}
async function upsert(table,row,onConflict){if(!supabase)return false;const{error}=await supabase.from(table).upsert(row,{onConflict});if(error)throw error;return true}
function persistDue(key,ms){const last=state.last_external_persist[key]||0;if(Date.now()-last<ms)return false;state.last_external_persist[key]=Date.now();return true}

async function persistDurable(){if(!supabase||!state.current)return;const s=state.current,i=s.intelligence||{},cg=s.external?.coinglass||{},liq=cg.liquidations||{};try{
  await insert('btc_market_snapshots',{observed_at:s.observed_at,composite_price_usd:s.price,composite_method:'Railway v4 direct WebSockets + CoinGlass all-exchange reconciliation',venue_count:s.venue_count,venue_dispersion_bps:s.venue_dispersion_bps,spot_cvd_usd_1m:num(s.spot?.reconciled?.m1),spot_cvd_usd_5m:num(s.spot?.reconciled?.m5),spot_cvd_usd_15m:num(s.spot?.reconciled?.m15),spot_cvd_usd_1h:num(s.spot?.reconciled?.m60),perp_cvd_usd_1m:num(s.perp?.reconciled?.m1),perp_cvd_usd_5m:num(s.perp?.reconciled?.m5),perp_cvd_usd_15m:num(s.perp?.reconciled?.m15),perp_cvd_usd_1h:num(s.perp?.reconciled?.m60),spot_perp_cvd_divergence_5m:(num(s.spot?.reconciled?.m5)??0)-(num(s.perp?.reconciled?.m5)??0),open_interest_usd:num(s.open_interest_usd),funding_oi_weighted:num(s.funding_oi_weighted),funding_volume_weighted:num(cg?.funding?.volume_weighted),long_liquidations_usd_1m:num(liq.long_1m_usd),short_liquidations_usd_1m:num(liq.short_1m_usd),long_liquidations_usd_5m:num(liq.long_5m_usd),short_liquidations_usd_5m:num(liq.short_5m_usd),liquidation_velocity_usd_per_min:num(liq.velocity_usd_per_min),nearest_liquidity_above_usd:num(liq?.map?.above?.price),nearest_liquidity_below_usd:num(liq?.map?.below?.price),nearest_liquidity_above_notional_usd:num(liq?.map?.above?.notional_usd),nearest_liquidity_below_notional_usd:num(liq?.map?.below?.notional_usd),driver_classification:i.driver_classification||'UNCLEAR',driver_confidence:num(i.regime_confidence),data_quality:num(i.data_quality),freshness:Object.fromEntries(Object.entries(s.external||{}).map(([k,v])=>[k,{status:v?.status,age_ms:v?.age_ms??null}])),source_health:s.source_health,raw:{engine:'railway-v4-single-authority',actual_liquidations:s.actual_liquidations,orderbook_aggregate:s.orderbook_aggregate,etf:s.etf}});
  await upsert('btc_signal_state',{singleton:true,updated_at:i.updated_at||now(),primary_regime:i.primary_regime,secondary_regime:i.secondary_regime,regime_confidence:num(i.regime_confidence),bull_score:num(i.bull_score),bear_score:num(i.bear_score),trade_confidence:num(i.trade_confidence),event_risk:i.event_risk,preferred_action:i.preferred_action,active_setup:i.active_setup||{},watchlist:i.watchlist||[],explainability:i.explainability||{}},'singleton');
  try{await insert('btc_feature_snapshots',{observed_at:s.observed_at,engine_version:'railway-v4-single-authority',price_usd:s.price,structure:s.structure,external:s.external,signal:i,coverage:s.coverage})}catch(e){if(!String(e).includes('btc_feature_snapshots'))throw e}
  if(Array.isArray(liq?.map?.clusters)&&liq.map.clusters.length&&persistDue('liq_clusters',60000))try{await insert('btc_liquidation_clusters',liq.map.clusters.slice(0,40).map(x=>({observed_at:s.observed_at,horizon:'1d',side:x.price>s.price?'above':'below',price_usd:x.price,estimated_notional_usd:x.notional_usd,distance_pct:x.distance_pct,provider:'CoinGlass',data_status:'ESTIMATED',methodology:'CoinGlass aggregated liquidation map: modelled positioning, not executed liquidations',raw:{}})))}catch(e){err(e,'supabase:liq_clusters')}
  if(i.active_setup){const key=JSON.stringify([i.active_setup.setup_type,i.active_setup.direction,Math.round(i.active_setup.stop_risk_level||0)]);if(key!==state.last_setup_key){state.last_setup_key=key;await insert('btc_setups',{status:'WATCH',setup_type:i.active_setup.setup_type,direction:i.active_setup.direction,time_horizon:'intraday',confidence:num(i.trade_confidence),data_quality:num(i.data_quality),entry_zone:i.active_setup.entry_zone,trigger_required:i.active_setup.trigger_required,invalidation:i.active_setup.invalidation,stop_risk_level:i.active_setup.stop_risk_level,targets:i.active_setup.targets,expected_rr:i.active_setup.expected_rr,key_levels:{liquidity:i.active_setup.liquidity_context,structure:s.structure?.levels},evidence:{confirmations:i.active_setup.confirmations,driver:i.active_setup.driver},contradictions:i.active_setup.contradictions,cancel_conditions:[i.active_setup.invalidation],expires_at:i.active_setup.expires_at})}}
  if(i.priority&&i.priority!=='INFO'){const key=`${i.priority}:${i.preferred_action}:${i.driver_classification}:${Math.round((i.trade_confidence||0)/5)*5}:${new Date().toISOString().slice(0,13)}`;if(key!==state.last_alert_key){state.last_alert_key=key;try{await insert('btc_alerts',{priority:i.priority,alert_type:i.active_setup?'SETUP_WATCH':'REGIME_EVENT_WATCH',dedupe_key:key,title:`BTC ${i.priority} — ${i.preferred_action}`,payload:{price:s.price,intelligence:i,event_calendar:s.external?.event_calendar}})}catch(e){if(!String(e).toLowerCase().includes('duplicate'))throw e}}}

  if(persistDue('options',60000)&&s.external?.options?.status!=='UNAVAILABLE')try{await insert('btc_options_snapshots',{observed_at:s.external.options.observed_at,source:'Deribit',dvol:num(s.external.options.dvol),atm_iv:num(s.external.options.atm_iv),put_call_oi_ratio:num(s.external.options.put_call_oi_ratio),put_call_volume_ratio:num(s.external.options.put_call_volume_ratio),total_open_interest:num(s.external.options.option_oi),expiries:s.external.options.expiries||[],raw:s.external.options})}catch(e){err(e,'supabase:options')}
  if(persistDue('cross_asset',60000)&&s.external?.cross_asset?.status!=='UNAVAILABLE')try{const x=s.external.cross_asset;await insert('btc_cross_asset_snapshots',{observed_at:x.observed_at,dxy:num(x.dxy?.price),nasdaq:num(x.nasdaq?.price),sp500:num(x.sp500?.price),vix:num(x.vix?.price),gold:num(x.gold?.price),wti:num(x.wti?.price),brent:num(x.brent?.price),usdjpy:num(x.usdjpy?.price),usdcnh:num(x.usdcnh?.price),crypto_equities:{mstr:x.mstr,coin:x.coin},raw:x})}catch(e){err(e,'supabase:cross_asset')}
  if(persistDue('onchain',300000)&&s.external?.onchain?.status!=='UNAVAILABLE')try{const x=s.external.onchain;await insert('btc_onchain_snapshots',{observed_at:x.observed_at,exchange_reserves:x.exchange_balances||{},miners:{},hash_rate:num(x.hash_rate?.values?.at?.(-1)?.y),difficulty:num(x.difficulty?.values?.at?.(-1)?.y),stablecoins:s.external.stablecoins||{},whales:x.whale_transfers||[],data_status:x.status==='LIVE'?'LIVE':'PARTIAL',raw:x})}catch(e){err(e,'supabase:onchain')}
  if(persistDue('prediction',120000)){const rows=[];for(const p of s.external?.prediction_markets?.polymarket||[])rows.push({observed_at:s.observed_at,provider:'POLYMARKET',market_id:String(p.id),title:p.title,liquidity:num(p.liquidity),volume_24h:num(p.volume24h),open_interest:num(p.open_interest),raw:p});for(const p of s.external?.prediction_markets?.kalshi||[])rows.push({observed_at:s.observed_at,provider:'KALSHI',market_id:String(p.ticker),title:p.title,bid:num(p.yes_bid),ask:num(p.yes_ask),volume_24h:num(p.volume_24h),open_interest:num(p.open_interest),closes_at:p.close_time||null,raw:p});if(rows.length)try{await insert('btc_prediction_market_snapshots',rows.slice(0,150))}catch(e){err(e,'supabase:prediction')}}
  if(persistDue('macro_events',3600000)){const events=s.external?.event_calendar?.upcoming||[];for(const e of events.slice(0,30))try{await upsert('btc_macro_events',{event_key:e.event_key,scheduled_at:e.scheduled_at,event_name:e.event_name,source:e.source,status:e.status,importance:e.importance,raw:e.raw||{},updated_at:now()},'event_key')}catch(x){err(x,'supabase:macro_event')}}
  state.last_supabase_at=now();
}catch(e){err(e,'persistDurable')}}

setInterval(()=>void clickhouseWriter.flushTrades().catch(e=>err(e,'clickhouse:trades')),750).unref();setInterval(()=>void clickhouseWriter.flushBooks().catch(e=>err(e,'clickhouse:books')),1000).unref();setInterval(()=>void tick(),Number(process.env.STATE_INTERVAL_MS||1000)).unref();setInterval(()=>void persistDurable(),Number(process.env.SUPABASE_INTERVAL_MS||15000)).unref();setInterval(()=>void persistClickHouseFeature(),60000).unref();

await structure.bootstrap();await market.start();external.start();calendar.start();void tick();
app.get('/health',async()=>({ok:true,engine:'railway-v4-single-authority',now:now(),started_at:state.started_at,redis:redisPublisher.health(),clickhouse:clickhouseWriter.health(),direct_sockets:market.sockets,external:Object.fromEntries(Object.entries(external.snapshot()).map(([k,v])=>[k,{status:v?.status,age_ms:v?.age_ms??null,error:v?.error||null}])),event_calendar:calendar.snapshot(),last_state_at:state.current?.observed_at||null,last_supabase_at:state.last_supabase_at,last_feature_at:state.last_feature_at,errors:[...market.errors.slice(-8),...state.errors.slice(-8)]}));
app.get('/state',async()=>state.current||{ok:false,status:'WARMING_UP'});app.get('/intelligence',async()=>({ok:!!state.current,engine:'railway-v4-single-authority',price:state.current?.price,intelligence:state.current?.intelligence,structure:state.current?.structure,liquidations:state.current?.liquidation_state,orderbook:state.current?.orderbook_aggregate,etf:state.current?.etf,options:state.current?.external?.options,macro:{fred:state.current?.external?.macro,bls:state.current?.external?.bls,calendar:state.current?.external?.event_calendar},cross_asset:state.current?.external?.cross_asset,onchain:state.current?.external?.onchain,stablecoins:state.current?.external?.stablecoins,prediction_markets:state.current?.external?.prediction_markets,news:state.current?.external?.news,coverage:state.current?.coverage}));
const port=Number(process.env.PORT||3000);app.listen({port,host:'0.0.0.0'}).then(()=>log.info({port},'BTC Global Intelligence v4 running')).catch(e=>{log.fatal(e);process.exit(1)});
for(const sig of ['SIGTERM','SIGINT'])process.on(sig,async()=>{log.info({sig},'shutdown');external.stop();calendar.stop();market.stop();await clickhouseWriter.flushAll();try{await redis.quit()}catch{}try{await clickhouse.close()}catch{}process.exit(0)});
