import { createClient as createClickHouseClient } from '@clickhouse/client';
import { createClient as createSupabaseClient } from '@supabase/supabase-js';
import Fastify from 'fastify';
import pino from 'pino';
import { createBoundedRedis, FlowAccumulator, RedisPublisher } from './redis-state.js';
import { ClickHouseWriter } from './clickhouse-writer.js';
import { SafeDirectMarketHub } from './direct-market-safe.js';
import { StructureEngine } from './structure-engine.js';
import { MicrostructureEngine } from './microstructure-engine.js';
import { ExternalV5Hub } from './external-v5.js';
import { MacroEventCalendar } from './event-calendar.js';
import { SignalEngineV5 } from './signal-v5.js';
import { SIGNAL_FAMILIES, REQUIRED_SOURCE_GROUPS } from './coverage.js';

const log=pino({level:process.env.LOG_LEVEL||'info'}),app=Fastify({logger:false}),num=v=>{const n=Number(v);return Number.isFinite(n)?n:null},now=()=>new Date().toISOString();
const redis=createBoundedRedis(process.env.REDIS_URL),redisPublisher=new RedisPublisher(redis,{bookPublishIntervalMs:Number(process.env.REDIS_BOOK_PUBLISH_MS||200)}),clickhouse=createClickHouseClient({url:process.env.CLICKHOUSE_URL,username:process.env.CLICKHOUSE_USER||'default',password:process.env.CLICKHOUSE_PASSWORD||'',database:process.env.CLICKHOUSE_DB||'btc',request_timeout:Number(process.env.CLICKHOUSE_REQUEST_TIMEOUT_MS||10000)}),clickhouseWriter=new ClickHouseWriter(clickhouse,{maxTradeBuffer:Number(process.env.MAX_TRADE_BUFFER||100000),maxBookBuffer:Number(process.env.MAX_BOOK_BUFFER||20000),maxQuarantineBatches:Number(process.env.MAX_QUARANTINE_BATCHES||200)}),supabase=process.env.SUPABASE_URL&&process.env.SUPABASE_SERVICE_ROLE_KEY?createSupabaseClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false}}):null;
const flow=new FlowAccumulator({retentionMinutes:Number(process.env.FLOW_RETENTION_MINUTES||240)}),structure=new StructureEngine(),signal=new SignalEngineV5(),market=new SafeDirectMarketHub({flow,clickhouseWriter,redisPublisher,structureEngine:structure,log,bookSampleMs:Number(process.env.BOOK_SAMPLE_MS||1000)}),micro=new MicrostructureEngine({market,flow,structure}),external=new ExternalV5Hub({getPrice:()=>state.current?.price}),calendar=new MacroEventCalendar();
const state={started_at:now(),current:null,errors:[],last_supabase_at:null,last_feature_at:null,last_setup_key:null,last_alert_key:null,last_external_persist:{}};
function error(e,context){const x={at:now(),context,error:String(e)};state.errors.push(x);if(state.errors.length>100)state.errors.shift();log.warn(x)}
function reconcile(core,ext){const cg=ext.coinglass||{},f=cg.flow||{},l=cg.liquidations||{};return{...core,spot:{...core.spot,reconciled:{m1:num(f.spot_cvd_1m)??core.spot.m1.delta_usd,m5:num(f.spot_cvd_5m)??core.spot.m5.delta_usd,m15:num(f.spot_cvd_15m)??core.spot.m15.delta_usd,m60:num(f.spot_cvd_1h)??core.spot.m60.delta_usd,source:cg.status==='LIVE'?'CoinGlass all-exchange':'direct-WebSocket fallback'}},perp:{...core.perp,reconciled:{m1:num(f.perp_cvd_1m)??core.perp.m1.delta_usd,m5:num(f.perp_cvd_5m)??core.perp.m5.delta_usd,m15:num(f.perp_cvd_15m)??core.perp.m15.delta_usd,m60:num(f.perp_cvd_1h)??core.perp.m60.delta_usd,source:cg.status==='LIVE'?'CoinGlass all-exchange':'direct-WebSocket fallback'}},open_interest_usd:num(cg?.open_interest?.total_usd)??core.open_interest_usd,funding_oi_weighted:num(cg?.funding?.oi_weighted)??core.funding_oi_weighted,liquidation_state:{actual_orders:core.actual_liquidations,aggregated_history:{long_1m_usd:num(l.long_1m_usd),short_1m_usd:num(l.short_1m_usd),long_5m_usd:num(l.long_5m_usd),short_5m_usd:num(l.short_5m_usd),velocity_usd_per_min:num(l.velocity_usd_per_min)},modelled_positioning:{map:l.map||null,heatmap:l.heatmap||null},integrity_note:'Actual liquidation executions and modelled liquidation positioning are separate signal classes.'},orderbook_aggregate:cg.orderbook||null,etf:cg.etf||null}}
async function tick(){try{const raw=market.core();if(!raw)return;const ext=external.snapshot();ext.event_calendar=calendar.snapshot();const core=reconcile(raw,ext),fullStructure=structure.snapshot(core.price),microState=micro.snapshot(core.price),adjusted={...core,spot:{...core.spot,m5:{...core.spot.m5,delta_usd:core.spot.reconciled?.m5??core.spot.m5.delta_usd}},perp:{...core.perp,m5:{...core.perp.m5,delta_usd:core.perp.reconciled?.m5??core.perp.m5.delta_usd}}},intelligence=signal.evaluateV5(adjusted,ext,fullStructure,microState);state.current={engine:'railway-v5-single-authority',observed_at:now(),...core,structure:fullStructure,microstructure:microState,external:ext,intelligence,coverage:{direct_websocket_venues:[...new Set(Object.keys(market.sockets).map(x=>x.split('_')[0]))],direct_socket_health:market.sockets,coinglass:ext.coinglass?.coverage||null,signal_families:SIGNAL_FAMILIES,required_source_groups:REQUIRED_SOURCE_GROUPS}};await redisPublisher.publishState(state.current)}catch(e){error(e,'tick')}}
async function feature(){if(!state.current)return;const s=state.current,i=s.intelligence||{},l=s.external?.coinglass?.liquidations||{};try{await clickhouse.insert({table:'intelligence_1m_v3',format:'JSONEachRow',values:[{minute:new Date(Math.floor(Date.now()/60000)*60000).toISOString().replace('T',' ').replace('Z',''),ingested_at:now(),price_usd:s.price,spot_cvd_1m:num(s.spot?.reconciled?.m1),spot_cvd_5m:num(s.spot?.reconciled?.m5),perp_cvd_1m:num(s.perp?.reconciled?.m1),perp_cvd_5m:num(s.perp?.reconciled?.m5),open_interest_usd:num(s.open_interest_usd),funding_oi_weighted:num(s.funding_oi_weighted),long_liq_5m_usd:num(l.long_5m_usd),short_liq_5m_usd:num(l.short_5m_usd),bull_score:num(i.bull_score),bear_score:num(i.bear_score),trade_confidence:num(i.trade_confidence),data_quality:num(i.data_quality),regime:String(i.primary_regime||'UNKNOWN'),driver:String(i.driver_classification||'UNCLEAR'),event_risk:String(i.event_risk||'LOW'),payload:JSON.stringify({structure:s.structure,microstructure:s.microstructure,external_health:Object.fromEntries(Object.entries(s.external||{}).map(([k,v])=>[k,{status:v?.status,age_ms:v?.age_ms??null}]))})}]});state.last_feature_at=now()}catch(e){error(e,'clickhouse:intelligence_1m')}}
async function ins(table,row){if(!supabase)return;const{error:e}=await supabase.from(table).insert(row);if(e)throw e}async function ups(table,row,onConflict){if(!supabase)return;const{error:e}=await supabase.from(table).upsert(row,{onConflict});if(e)throw e}function due(k,ms){const l=state.last_external_persist[k]||0;if(Date.now()-l<ms)return false;state.last_external_persist[k]=Date.now();return true}
async function durable(){if(!supabase||!state.current)return;const s=state.current,i=s.intelligence||{},cg=s.external?.coinglass||{},l=cg.liquidations||{};try{
  await ins('btc_market_snapshots',{observed_at:s.observed_at,composite_price_usd:s.price,composite_method:'Railway v5 direct WebSockets + CoinGlass all-exchange reconciliation',venue_count:s.venue_count,venue_dispersion_bps:s.venue_dispersion_bps,spot_cvd_usd_1m:num(s.spot?.reconciled?.m1),spot_cvd_usd_5m:num(s.spot?.reconciled?.m5),spot_cvd_usd_15m:num(s.spot?.reconciled?.m15),spot_cvd_usd_1h:num(s.spot?.reconciled?.m60),perp_cvd_usd_1m:num(s.perp?.reconciled?.m1),perp_cvd_usd_5m:num(s.perp?.reconciled?.m5),perp_cvd_usd_15m:num(s.perp?.reconciled?.m15),perp_cvd_usd_1h:num(s.perp?.reconciled?.m60),spot_perp_cvd_divergence_5m:(num(s.spot?.reconciled?.m5)??0)-(num(s.perp?.reconciled?.m5)??0),open_interest_usd:num(s.open_interest_usd),funding_oi_weighted:num(s.funding_oi_weighted),funding_volume_weighted:num(cg?.funding?.volume_weighted),long_liquidations_usd_1m:num(l.long_1m_usd),short_liquidations_usd_1m:num(l.short_1m_usd),long_liquidations_usd_5m:num(l.long_5m_usd),short_liquidations_usd_5m:num(l.short_5m_usd),liquidation_velocity_usd_per_min:num(l.velocity_usd_per_min),nearest_liquidity_above_usd:num(l?.map?.above?.price),nearest_liquidity_below_usd:num(l?.map?.below?.price),nearest_liquidity_above_notional_usd:num(l?.map?.above?.notional_usd),nearest_liquidity_below_notional_usd:num(l?.map?.below?.notional_usd),driver_classification:i.driver_classification||'UNCLEAR',driver_confidence:num(i.regime_confidence),data_quality:num(i.data_quality),freshness:Object.fromEntries(Object.entries(s.external||{}).map(([k,v])=>[k,{status:v?.status,age_ms:v?.age_ms??null}])),source_health:s.source_health,raw:{engine:'railway-v5-single-authority',actual_liquidations:s.actual_liquidations,orderbook_aggregate:s.orderbook_aggregate,etf:s.etf,microstructure:s.microstructure}});
  await ups('btc_signal_state',{singleton:true,updated_at:i.updated_at||now(),primary_regime:i.primary_regime,secondary_regime:i.secondary_regime,regime_confidence:num(i.regime_confidence),bull_score:num(i.bull_score),bear_score:num(i.bear_score),trade_confidence:num(i.trade_confidence),event_risk:i.event_risk,preferred_action:i.preferred_action,active_setup:i.active_setup||{},watchlist:i.watchlist||[],explainability:i.explainability||{}},'singleton');
  try{await ins('btc_feature_snapshots',{observed_at:s.observed_at,engine_version:'railway-v5-single-authority',price_usd:s.price,structure:s.structure,external:s.external,signal:i,coverage:s.coverage})}catch(e){if(!String(e).includes('btc_feature_snapshots'))throw e}
  if(Array.isArray(l?.map?.clusters)&&l.map.clusters.length&&due('clusters',60000))try{await ins('btc_liquidation_clusters',l.map.clusters.slice(0,40).map(x=>({observed_at:s.observed_at,horizon:'1d',side:x.price>s.price?'above':'below',price_usd:x.price,estimated_notional_usd:x.notional_usd,distance_pct:x.distance_pct,provider:'CoinGlass',data_status:'ESTIMATED',methodology:'Aggregated liquidation map; modelled positioning, not actual forced-liquidation executions',raw:{}})))}catch(e){error(e,'db:clusters')}
  if(i.active_setup){const k=JSON.stringify([i.active_setup.setup_type,i.active_setup.direction,Math.round(i.active_setup.stop_risk_level||0)]);if(k!==state.last_setup_key){state.last_setup_key=k;await ins('btc_setups',{status:'WATCH',setup_type:i.active_setup.setup_type,direction:i.active_setup.direction,time_horizon:'intraday',confidence:num(i.trade_confidence),data_quality:num(i.data_quality),entry_zone:i.active_setup.entry_zone,trigger_required:i.active_setup.trigger_required,invalidation:i.active_setup.invalidation,stop_risk_level:i.active_setup.stop_risk_level,targets:i.active_setup.targets,expected_rr:i.active_setup.expected_rr,key_levels:i.active_setup.key_levels||{},evidence:{confirmations:i.active_setup.confirmations,driver:i.active_setup.driver},contradictions:i.active_setup.contradictions,cancel_conditions:[i.active_setup.invalidation],expires_at:i.active_setup.expires_at})}}
  if(i.priority&&i.priority!=='INFO'){const k=`${i.priority}:${i.preferred_action}:${i.driver_classification}:${Math.round((i.trade_confidence||0)/5)*5}:${new Date().toISOString().slice(0,13)}`;if(k!==state.last_alert_key){state.last_alert_key=k;try{await ins('btc_alerts',{priority:i.priority,alert_type:i.active_setup?'SETUP_WATCH':'REGIME_EVENT_WATCH',dedupe_key:k,title:`BTC ${i.priority} — ${i.preferred_action}`,payload:{price:s.price,intelligence:i,event_calendar:s.external?.event_calendar}})}catch(e){if(!String(e).toLowerCase().includes('duplicate'))throw e}}}
  if(due('options',60000)&&s.external?.options?.status!=='UNAVAILABLE')try{const x=s.external.options;await ins('btc_options_snapshots',{observed_at:x.observed_at,source:'Deribit+CoinGlass',dvol:num(x.dvol),atm_iv:num(x.atm_iv),put_call_oi_ratio:num(x.put_call_oi_ratio),put_call_volume_ratio:num(x.put_call_volume_ratio),total_open_interest:num(x.option_oi),expected_move:x.expected_move||{},term_structure:x.term_structure||[],skew:x.skew||{},expiries:x.term_structure||[],gamma_context:x.gamma_context||{},max_pain:x.max_pain||{},data_status:x.status==='LIVE'?'LIVE':'PARTIAL',raw:x})}catch(e){error(e,'db:options')}
  if(due('cross',60000)&&s.external?.cross_asset?.status!=='UNAVAILABLE')try{const x=s.external.cross_asset;await ins('btc_cross_asset_snapshots',{observed_at:x.observed_at,dxy:num(x.dxy?.price),nasdaq:num(x.nasdaq?.price),sp500:num(x.sp500?.price),vix:num(x.vix?.price),gold:num(x.gold?.price),wti:num(x.wti?.price),brent:num(x.brent?.price),usdjpy:num(x.usdjpy?.price),usdcnh:num(x.usdcnh?.price),crypto_equities:{mstr:x.mstr,coin:x.coin},raw:x})}catch(e){error(e,'db:cross')}
  if(due('onchain',300000)&&s.external?.onchain?.status!=='UNAVAILABLE')try{const x=s.external.onchain;await ins('btc_onchain_snapshots',{observed_at:x.observed_at,exchange_reserves:x.exchange_balances||{},miners:{},hash_rate:num(x.hash_rate?.values?.at?.(-1)?.y),difficulty:num(x.difficulty?.values?.at?.(-1)?.y),stablecoins:s.external.stablecoins||{},whales:x.whale_transfers||[],data_status:x.status==='LIVE'?'LIVE':'PARTIAL',raw:x})}catch(e){error(e,'db:onchain')}
  if(due('prediction',120000)){const rows=[];for(const p of s.external?.prediction_markets?.polymarket||[])rows.push({observed_at:s.observed_at,provider:'POLYMARKET',market_id:String(p.id),title:p.title,liquidity:num(p.liquidity),volume_24h:num(p.volume24h),open_interest:num(p.open_interest),raw:p});for(const p of s.external?.prediction_markets?.kalshi||[])rows.push({observed_at:s.observed_at,provider:'KALSHI',market_id:String(p.ticker),title:p.title,bid:num(p.yes_bid),ask:num(p.yes_ask),volume_24h:num(p.volume_24h),open_interest:num(p.open_interest),closes_at:p.close_time||null,raw:p});if(rows.length)try{await ins('btc_prediction_market_snapshots',rows.slice(0,150))}catch(e){error(e,'db:prediction')}}
  if(due('macro',3600000))for(const e of s.external?.event_calendar?.upcoming?.slice?.(0,30)||[])try{await ups('btc_macro_events',{event_key:e.event_key,scheduled_at:e.scheduled_at,event_name:e.event_name,source:e.source,status:e.status,importance:e.importance,raw:e.raw||{},updated_at:now()},'event_key')}catch(x){error(x,'db:macro_event')}
  state.last_supabase_at=now();
}catch(e){error(e,'durable')}}
setInterval(()=>void clickhouseWriter.flushTrades().catch(e=>error(e,'clickhouse:trades')),750).unref();setInterval(()=>void clickhouseWriter.flushBooks().catch(e=>error(e,'clickhouse:books')),1000).unref();setInterval(()=>void tick(),Number(process.env.STATE_INTERVAL_MS||1000)).unref();setInterval(()=>void durable(),Number(process.env.SUPABASE_INTERVAL_MS||15000)).unref();setInterval(()=>void feature(),60000).unref();
await structure.bootstrap();await market.start();external.start();calendar.start();void tick();
app.get('/health',async()=>({ok:true,engine:'railway-v5-single-authority',now:now(),started_at:state.started_at,redis:redisPublisher.health(),clickhouse:clickhouseWriter.health(),direct_sockets:market.sockets,external:Object.fromEntries(Object.entries(external.snapshot()).map(([k,v])=>[k,{status:v?.status,age_ms:v?.age_ms??null,error:v?.error||null}])),event_calendar:calendar.snapshot(),last_state_at:state.current?.observed_at||null,last_supabase_at:state.last_supabase_at,last_feature_at:state.last_feature_at,errors:[...market.errors.slice(-8),...state.errors.slice(-8)]}));
app.get('/state',async()=>state.current||{ok:false,status:'WARMING_UP'});app.get('/intelligence',async()=>({ok:!!state.current,engine:'railway-v5-single-authority',price:state.current?.price,intelligence:state.current?.intelligence,structure:state.current?.structure,microstructure:state.current?.microstructure,liquidations:state.current?.liquidation_state,orderbook:state.current?.orderbook_aggregate,etf:state.current?.etf,options:state.current?.external?.options,macro:{fred:state.current?.external?.macro,bls:state.current?.external?.bls,calendar:state.current?.external?.event_calendar},cross_asset:state.current?.external?.cross_asset,onchain:state.current?.external?.onchain,stablecoins:state.current?.external?.stablecoins,prediction_markets:state.current?.external?.prediction_markets,news:state.current?.external?.news,coverage:state.current?.coverage}));
const port=Number(process.env.PORT||3000);app.listen({port,host:'0.0.0.0'}).then(()=>log.info({port},'BTC Global Intelligence v5 running')).catch(e=>{log.fatal(e);process.exit(1)});for(const sig of ['SIGTERM','SIGINT'])process.on(sig,async()=>{log.info({sig},'shutdown');external.stop();calendar.stop();market.stop();await clickhouseWriter.flushAll();try{await redis.quit()}catch{}try{await clickhouse.close()}catch{}process.exit(0)});
